[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
# テスト対象のディレクトリ（再帰的に探索される）
testpaths = ["tests"]

# テストファイル名のパターン
# - 通常のユニットテスト: test_*.py
# - E2E テスト: *_e2e.py
python_files = ["test_*.py", "*_e2e.py"]

# （必要に応じてテストクラス／関数のパターンを指定可能）
# python_classes = ["Test*"]
# python_functions = ["test_*"]

# asyncio 用のデフォルト fixture loop scope を function に固定
asyncio_default_fixture_loop_scope = "function"

# pandas の 'H' deprecated 警告を抑制
filterwarnings = [
  "ignore:'H' is deprecated and will be removed in a future version.*:FutureWarning"
]

[project]
name = "crypto-bot"
version = "0.1.0"
description = "汎用暗号資産トレーディングボット"
requires-python = ">=3.8"

dependencies = [
    # --- ベース ---
    "numpy>=1.23.0,<2.0",
    "pandas>=1.3.0",
    "pandas-ta>=0.3.14b0",
    "scipy>=1.7.0",
    "pyyaml>=6.0",

    # --- CLI / ランタイム追加 ---
    "click>=8.1.0",
    "ccxt>=2.10.0",
    "python-dotenv>=1.0.0",
    "tenacity>=8.2.0",

    # --- 機械学習関連 ---
    "scikit-learn>=1.2.0",
    "optuna>=3.0.0",
    "lightgbm>=4.0.0",
    "xgboost>=1.7.0",

    # --- プロット用 ---
    "matplotlib>=3.5.0",

    # --- ストリーミング (必要なら) ---
    "websockets>=11.0.0",
]
