[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88   # ★ isort の行長も black に合わせる
skip_gitignore = true  # .gitignore に載るファイル/フォルダは自動スキップ

[tool.pytest.ini_options]
# テスト対象のディレクトリ（再帰的に探索される）
testpaths = ["tests"]

# テストファイル名のパターン
python_files = ["test_*.py", "*_e2e.py"]

# asyncio 用のデフォルト fixture loop scope を function に固定
asyncio_default_fixture_loop_scope = "function"

# pandas の 'H' deprecated 警告を抑制
filterwarnings = [
  "ignore:'H' is deprecated and will be removed in a future version.*:FutureWarning"
]

[project]
name = "crypto-bot"
version = "0.1.0"
description = "汎用暗号資産トレーディングボット"
# Python 3.11 と 3.12 だけをサポートするので、ここも狭めておく
requires-python = ">=3.11,<3.13"

dependencies = [
    # --- ベース ---
    "numpy>=1.23.0,<2.0",
    "pandas>=1.3.0",
    "pandas-ta>=0.3.14b0",
    "scipy>=1.7.0",
    "pyyaml>=6.0",

    # --- CLI / ランタイム追加 ---
    "click>=8.1.0",
    "ccxt>=2.10.0",
    "python-dotenv>=1.0.0",
    "tenacity>=8.2.0",

    # --- 機械学習関連 ---
    "scikit-learn>=1.2.0",
    "optuna>=3.0.0",
    "lightgbm>=4.0.0",
    "xgboost>=1.7.0",

    # --- プロット用 ---
    "matplotlib>=3.5.0",

    # --- ストリーミング (必要なら) ---
    "websockets>=11.0.0",
    "google-cloud-monitoring>=2.18.0",
]

# build-system テーブルが未記載の場合、必要に応じて Poetry / Hatchling 等を追加してください。
