[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88   # ★ isort の行長も black に合わせる
skip_gitignore = true  # .gitignore に載るファイル/フォルダは自動スキップ

[tool.pytest.ini_options]
# テスト対象のディレクトリ（再帰的に探索される）
testpaths = ["tests"]

# テストファイル名のパターン
python_files = ["test_*.py", "*_e2e.py"]

# asyncio 用のデフォルト fixture loop scope を function に固定
asyncio_default_fixture_loop_scope = "function"

# pandas の 'H' deprecated 警告を抑制
filterwarnings = [
  "ignore:'H' is deprecated and will be removed in a future version.*:FutureWarning"
]

[project]
name = "crypto-bot"
version = "0.1.0"
description = "汎用暗号資産トレーディングボット"
# Python 3.11 と 3.12 だけをサポートするので、ここも狭めておく
requires-python = ">=3.11,<3.13"

[tool.setuptools]
packages = ["crypto_bot"]

# build-system テーブルが未記載の場合、必要に応じて Poetry / Hatchling 等を追加してください。

# ------------------------------------------------------------
# Bot が Cloud Run で HTTP /healthz を返すための軽量 API 依存
# ------------------------------------------------------------
[project.optional-dependencies]
api = [
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.29.0",
    "httpx>=0.27.0",  # FastAPI テストクライアント用
]
