# Production environment values
environment: "prod"
replicaCount: 3

config:
  mode: "live"
  logLevel: "INFO"
  healthCheckInterval: 60
  startupProbeDelay: 120

resources:
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60

podDisruptionBudget:
  enabled: true
  minAvailable: 2

healthchecks:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 60
  readiness:
    initialDelaySeconds: 60
    periodSeconds: 20
  startup:
    initialDelaySeconds: 30
    failureThreshold: 24

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "crypto-bot-ip"
    networking.gke.io/managed-certificates: "crypto-bot-ssl-cert"
  hosts:
    - host: crypto-bot.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: crypto-bot-tls
      hosts:
        - crypto-bot.example.com

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
  prometheusRule:
    enabled: true

# Production-specific tolerations for dedicated nodes
tolerations:
  - key: "node-role.kubernetes.io/crypto-bot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# Production node selector
nodeSelector:
  node-role.kubernetes.io/crypto-bot: "true"