# Development environment values
environment: "dev"
replicaCount: 1

config:
  mode: "paper"
  logLevel: "DEBUG"
  healthCheckInterval: 15
  startupProbeDelay: 30

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 1

healthchecks:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 15
    periodSeconds: 10
  startup:
    initialDelaySeconds: 10
    failureThreshold: 6

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: crypto-bot-dev.local
      paths:
        - path: /
          pathType: Prefix

monitoring:
  enabled: true