# Default values for crypto-bot
# This is a YAML-formatted file.

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# Image configuration
image:
  registry: ghcr.io
  repository: nao-namake/crypto-bot
  tag: "latest"
  pullPolicy: Always

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

# Application configuration
config:
  mode: "paper"  # paper, live
  logLevel: "INFO"
  healthCheckInterval: 30
  startupProbeDelay: 60
  metricsEnabled: true
  metricsPort: 8080
  
  # Trading configuration
  trading:
    exchange: "bybit_testnet"
    symbol: "BTC/USDT"
    interval: "1h"
    limit: 1000
    
  # Strategy configuration
  strategy:
    type: "single"  # single, multi
    name: "ml"
    threshold: 0.1
    modelPath: "model/calibrated_model.pkl"
    
  # Risk management
  risk:
    baseRisk: 0.02
    dynamicPositionSizing: true
    maxPositionSize: 0.1
    stopLossAtrMultiplier: 2.0
    
  # ML features
  ml:
    extraFeatures:
      - rsi
      - macd
      - volume_zscore
      - hour_of_day
      - day_of_week

# Secrets configuration
secrets:
  create: true
  # These will be base64 encoded
  bybitTestnetApiKey: ""
  bybitTestnetApiSecret: ""
  bybitLiveApiKey: ""
  bybitLiveApiSecret: ""
  bitbankApiKey: ""
  bitbankApiSecret: ""
  bitflyerApiKey: ""
  bitflyerApiSecret: ""
  okcoinjpApiKey: ""
  okcoinjpApiSecret: ""
  gcpCredentialsJson: ""

# Deployment configuration
replicaCount: 2

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations:
  - key: "node.kubernetes.io/spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# Affinity
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - crypto-bot
        topologyKey: kubernetes.io/hostname

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  metricsPort: 8080
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: crypto-bot.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Health checks
healthchecks:
  liveness:
    enabled: true
    path: /healthz
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  readiness:
    enabled: true
    path: /ready
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  startup:
    enabled: true
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 12
    successThreshold: 1

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: 30s
    scrapeTimeout: 10s
  prometheusRule:
    enabled: false
    namespace: ""

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

# Pod labels
podLabels: {}

# Environment-specific overrides
# These can be overridden in values-dev.yaml, values-prod.yaml, etc.
environment: "default"