# Development: ローカル開発環境設定
# 
# Phase 1-8 開発・テスト用の安全な設定
# ペーパートレード・高頻度ログ・デバッグ機能有効

# システム基本設定
system:
  name: "crypto-bot-development"
  version: "dev-latest"
  mode: "paper"
  debug: true
  log_level: "DEBUG"

# 取引所設定（開発用）
exchange:
  name: "bitbank"
  symbol: "BTC/JPY"
  leverage: 1.0  # 最小レバレッジ
  
  # API設定（開発用・制限なし）
  api_key: "${BITBANK_API_KEY_DEV}"
  api_secret: "${BITBANK_API_SECRET_DEV}"
  sandbox: false  # 実際のレート取得（注文は行わない）
  
  # API制限（開発用・高頻度）
  rate_limit: 10000   # 10秒制限
  timeout: 30000      # 30秒タイムアウト
  enable_rate_limit: true
  retries: 5

# データ設定（開発用・高頻度更新）
data:
  timeframes: ["15m", "1h", "4h"]
  since_hours: 48     # 48時間分（短期）
  limit: 50           # 50件制限
  
  cache:
    enabled: true
    ttl_minutes: 1    # 1分TTL（高頻度更新）
    max_size: 500
    disk_cache: false # ディスクキャッシュ無効
    retention_days: 1

# 特徴量設定（開発用・最小限）
features:
  mode: "development"
  
  basic:
    - "close"
    - "volume" 
    - "returns_1"
  
  technical:
    - "rsi_14"
    - "macd"
    - "atr_14"
    - "ema_20"
  
  anomaly:
    - "zscore"

# 戦略設定（開発用・単純化）
strategies:
  enabled:
    - "atr_based"    # 主要戦略のみテスト
  
  weights:
    atr_based: 1.0   # 単一戦略テスト
  
  consensus:
    required_agreement: 0.5    # 50%合意（緩和）
    confidence_threshold: 0.3  # 低信頼度でもテスト

# 機械学習設定（開発用・緩和）
ml:
  ensemble_enabled: false      # MLアンサンブル無効
  confidence_threshold: 0.3    # 30%（低閾値）
  
  models:
    - "lgbm"  # 単一モデルテスト
  
  model_weights:
    - 1.0
  
  prediction:
    lookback_periods: 50
    retrain_frequency: "never"  # 開発中は再学習なし

# リスク管理設定（開発用・安全）
risk:
  # Kelly基準（極めて保守的）
  kelly_criterion:
    max_position_ratio: 0.001   # 最大0.1%
    safety_factor: 0.1          # Kelly値の10%
    min_trades_for_kelly: 100   # 多くのデータ必要
  
  # 開発用リスク設定
  risk_per_trade: 0.001         # 0.1%
  kelly_max_fraction: 0.001     # 0.1%
  max_drawdown: 0.05           # 5%
  stop_loss_atr_multiplier: 0.5 # 0.5×ATR
  consecutive_loss_limit: 2    # 連続2損失で停止
  
  # 統合判定閾値（緩和）
  risk_thresholds:
    min_ml_confidence: 0.2         # 最小ML信頼度20%
    risk_threshold_deny: 0.9       # 90%以上でDENY
    risk_threshold_conditional: 0.3 # 30%以上で条件付き

# 注文実行設定（ペーパートレードのみ）
execution:
  mode: "paper"
  
  order:
    default_type: "market"
    slippage_tolerance: 0.001    # 0.1%
    max_retry: 3
    retry_delay: 1.0
  
  latency:
    target_ms: 2000              # 2秒以内（緩和）
    warning_ms: 1000             # 1秒警告
    critical_ms: 5000            # 5秒クリティカル

# 開発専用設定
development:
  min_order_size: 0.0001        # 最小注文サイズ
  max_order_size: 0.0001        # 開発は最小固定
  trade_interval: 30            # 30秒間隔（高頻度テスト）
  margin_trading: false         # 現物のみ
  
  daily_trade_limit: 100        # 1日100回まで
  max_daily_loss: 0.01          # 1日最大1%損失
  emergency_stop_loss: 0.02     # 緊急停止2%

# ログ設定（詳細化）
logging:
  level: "DEBUG"
  file_enabled: true
  discord_enabled: false        # 開発中はDiscord通知無効
  retention_days: 7             # 7日保存
  
  file:
    enabled: true
    path: "logs/development"
    rotation: "hourly"          # 1時間ごとローテーション
    retention_days: 7
    max_size_mb: 50
  
  discord:
    enabled: false              # 開発環境ではDiscord通知無効

# 監視・ヘルスチェック（高頻度）
monitoring:
  health_check:
    enabled: true
    interval_seconds: 5         # 5秒間隔
    timeout_seconds: 2
    
  performance:
    enabled: true
    metrics_interval: 30        # 30秒間隔

# 開発用目標指標
targets:
  monthly_profit_target: 0      # 利益目標なし（テスト目的）
  max_monthly_trades: 3000      # 多頻度テスト
  target_win_rate: 0.4          # 40%（緩和）
  target_sharpe_ratio: 0.5      # 0.5（緩和）
  
  evaluation_period_days: 1     # 1日評価
  min_trades_for_evaluation: 10 # 最低10取引

# セキュリティ設定（開発用）
security:
  api_key_rotation_days: 365    # 1年（長期間）
  max_api_calls_per_hour: 3600  # 高頻度許可
  emergency_contacts:
    - "dev@example.com"