# Development: テスト環境設定
# 
# Phase 9-2 実取引テスト用の設定
# 最小単位での安全なテスト・包括的ログ・Discord通知有効

# システム基本設定
system:
  name: "crypto-bot-testing"
  version: "test-9.2.0"
  mode: "live"  # 実取引テスト
  debug: true
  log_level: "INFO"

# 取引所設定（テスト用）
exchange:
  name: "bitbank"
  symbol: "BTC/JPY"
  leverage: 1.0  # 最小レバレッジ
  
  # API設定（実取引）
  api_key: "${BITBANK_API_KEY}"
  api_secret: "${BITBANK_API_SECRET}"
  sandbox: false
  
  # API制限（慎重）
  rate_limit: 30000
  timeout: 90000
  enable_rate_limit: true
  retries: 3

# データ設定（テスト用）
data:
  timeframes: ["15m", "1h", "4h"]
  since_hours: 72      # 3日分
  limit: 100
  
  cache:
    enabled: true
    ttl_minutes: 5
    max_size: 1000
    disk_cache: true
    retention_days: 30

# 特徴量設定（最小限）
features:
  mode: "testing"
  
  basic:
    - "close"
    - "volume" 
    - "returns_1"
  
  technical:
    - "rsi_14"
    - "macd"
    - "atr_14"
    - "ema_20"
  
  anomaly:
    - "zscore"

# 戦略設定（テスト用・保守的）
strategies:
  enabled:
    - "atr_based"
    - "mochipoy_alert"
  
  weights:
    atr_based: 0.7
    mochipoy_alert: 0.3
  
  consensus:
    required_agreement: 0.8    # 80%合意（厳格）
    confidence_threshold: 0.6

# 機械学習設定（テスト用）
ml:
  ensemble_enabled: true
  confidence_threshold: 0.7    # 70%（厳格）
  
  models:
    - "lgbm"
    - "xgb"
  
  model_weights:
    - 0.6
    - 0.4
  
  prediction:
    lookback_periods: 100
    retrain_frequency: "weekly"

# リスク管理設定（テスト用・極めて保守的）
risk:
  # Kelly基準（極めて保守的）
  kelly_criterion:
    max_position_ratio: 0.005   # 最大0.5%
    safety_factor: 0.3          # Kelly値の30%
    min_trades_for_kelly: 50
  
  # テスト用リスク設定
  risk_per_trade: 0.002         # 0.2%
  kelly_max_fraction: 0.005     # 0.5%
  max_drawdown: 0.05           # 5%
  stop_loss_atr_multiplier: 0.8 # 0.8×ATR
  consecutive_loss_limit: 2    # 連続2損失で停止
  
  # 統合判定閾値（厳格）
  risk_thresholds:
    min_ml_confidence: 0.7         # 最小ML信頼度70%
    risk_threshold_deny: 0.6       # 60%以上でDENY（厳格）
    risk_threshold_conditional: 0.4 # 40%以上で条件付き

# 注文実行設定（実取引・最小単位）
execution:
  mode: "live"
  
  order:
    default_type: "market"
    slippage_tolerance: 0.0003   # 0.03%（厳格）
    max_retry: 5
    retry_delay: 2.0
  
  latency:
    target_ms: 800
    warning_ms: 400
    critical_ms: 1500

# テスト専用設定
testing:
  min_order_size: 0.0001        # 最小注文サイズ固定
  max_order_size: 0.0001        # テストは最小固定
  trade_interval: 300           # 5分間隔（慎重）
  margin_trading: true          # 信用取引
  force_margin_mode: true
  
  daily_trade_limit: 5          # 1日5回まで
  max_daily_loss: 0.01          # 1日最大1%損失
  emergency_stop_loss: 0.02     # 緊急停止2%
  
  # テスト期間制限
  max_test_duration_hours: 24   # 最大24時間
  auto_stop_enabled: true       # 自動停止有効

# ログ設定（包括的・Discord通知有効）
logging:
  level: "INFO"
  file_enabled: true
  discord_enabled: true         # テスト結果Discord通知
  retention_days: 30
  
  file:
    enabled: true
    path: "logs/testing"
    rotation: "daily"
    retention_days: 30
    max_size_mb: 100
  
  discord:
    enabled: true
    webhook_url: "${DISCORD_WEBHOOK_URL}"
    
    levels:
      critical: true
      warning: true
      info: true              # テスト情報も通知

# 監視・ヘルスチェック（高頻度）
monitoring:
  health_check:
    enabled: true
    interval_seconds: 10        # 10秒間隔
    timeout_seconds: 3
    
  performance:
    enabled: true
    metrics_interval: 60        # 1分間隔

# テスト用目標指標
targets:
  # テスト成功指標
  min_successful_trades: 3      # 最低3回成功取引
  max_failed_trades: 1          # 最大1回失敗許容
  target_execution_time_ms: 800 # 800ms以内実行
  
  evaluation_period_hours: 4    # 4時間評価
  min_trades_for_evaluation: 3  # 最低3取引

# セキュリティ設定（テスト用）
security:
  api_key_rotation_days: 30
  max_api_calls_per_hour: 500   # 制限（テスト用）
  emergency_contacts:
    - "test@example.com"
  
  # テスト用緊急停止条件
  emergency_conditions:
    max_loss_amount_jpy: 1000   # 1,000円損失で緊急停止
    max_consecutive_errors: 3   # 連続3エラーで停止
    api_error_threshold: 5      # 5回APIエラーで停止