# Validation: Phase 12 本番移行前検証設定
# 
# Phase 12 CI/CD統合・手動実行監視・段階的デプロイ対応の実運用検証用設定
# 段階的資金投入前の最終確認・パフォーマンス測定

# システム基本設定
system:
  name: "crypto-bot-validation"
  version: "11.0.0"
  mode: "live"
  debug: false
  log_level: "INFO"

# 取引所設定（本番同等）
exchange:
  name: "bitbank"
  symbol: "BTC/JPY"
  leverage: 1.0
  
  # API設定（本番同等）
  api_key: "${BITBANK_API_KEY}"
  api_secret: "${BITBANK_API_SECRET}"
  sandbox: false
  
  # API制限（本番同等）
  rate_limit: 30000
  timeout: 90000
  enable_rate_limit: true
  retries: 3

# データ設定（本番同等）
data:
  timeframes: ["15m", "1h", "4h"]
  since_hours: 96
  limit: 100
  
  cache:
    enabled: true
    ttl_minutes: 5
    max_size: 1000
    disk_cache: true
    retention_days: 90

# 特徴量設定（本番同等）
features:
  mode: "validation"
  
  basic:
    - "close"
    - "volume" 
    - "returns_1"
  
  technical:
    - "rsi_14"
    - "macd"
    - "atr_14"
    - "bb_position"
    - "ema_20"
    - "ema_50"
  
  anomaly:
    - "zscore"
    - "volume_ratio"
    - "market_stress"

# 戦略設定（本番同等）
strategies:
  enabled:
    - "atr_based"
    - "mochipoy_alert"
    - "multi_timeframe"
    - "fibonacci_retracement"
  
  weights:
    atr_based: 0.4
    mochipoy_alert: 0.3
    multi_timeframe: 0.2
    fibonacci_retracement: 0.1
  
  consensus:
    required_agreement: 0.6
    confidence_threshold: 0.5

# 機械学習設定（本番同等）
ml:
  ensemble_enabled: true
  confidence_threshold: 0.5
  
  models:
    - "lgbm"
    - "xgb"
    - "rf"
  
  model_weights:
    - 0.5
    - 0.3
    - 0.2
  
  prediction:
    lookback_periods: 100
    retrain_frequency: "weekly"

# リスク管理設定（検証用・保守的）
risk:
  # Kelly基準（保守的）
  kelly_criterion:
    max_position_ratio: 0.01    # 最大1%（検証用）
    safety_factor: 0.5          # Kelly値の50%
    min_trades_for_kelly: 20
  
  # 検証用リスク設定
  risk_per_trade: 0.005         # 0.5%
  kelly_max_fraction: 0.01      # 1%
  max_drawdown: 0.10           # 10%
  stop_loss_atr_multiplier: 1.0 # 1.0×ATR
  consecutive_loss_limit: 3    # 連続3損失で停止
  
  # 統合判定閾値（バランス）
  risk_thresholds:
    min_ml_confidence: 0.5         # 最小ML信頼度50%
    risk_threshold_deny: 0.75      # 75%以上でDENY
    risk_threshold_conditional: 0.5 # 50%以上で条件付き

# 注文実行設定（検証用）
execution:
  mode: "live"
  
  order:
    default_type: "limit"         # 指値注文優先
    slippage_tolerance: 0.0005   # 0.05%
    max_retry: 4
    retry_delay: 1.5
  
  latency:
    target_ms: 1000
    warning_ms: 500
    critical_ms: 2000

# 検証専用設定
validation:
  min_order_size: 0.0001        # 最小注文サイズ
  max_order_size: 0.0003        # 最大0.0003 BTC
  trade_interval: 120           # 2分間隔
  margin_trading: true
  force_margin_mode: true
  
  daily_trade_limit: 20         # 1日20回まで
  max_daily_loss: 0.02          # 1日最大2%損失
  emergency_stop_loss: 0.05     # 緊急停止5%
  
  # 検証期間・条件
  validation_period_days: 7     # 7日間検証
  min_trades_for_validation: 30 # 最低30取引必要
  
  # 成功条件
  required_performance:
    min_win_rate: 0.55          # 勝率55%以上
    max_drawdown: 0.08          # ドローダウン8%以内
    min_profit_jpy: 2000        # 最低2,000円利益
    min_sharpe_ratio: 0.8       # シャープレシオ0.8以上

# ログ設定（検証用・詳細）
logging:
  level: "INFO"
  file_enabled: true
  discord_enabled: true
  retention_days: 30
  
  file:
    enabled: true
    path: "logs/validation"
    rotation: "daily"
    retention_days: 30
    max_size_mb: 200
  
  discord:
    enabled: true
    webhook_url: "${DISCORD_WEBHOOK_URL}"
    
    levels:
      critical: true
      warning: true
      info: false             # 重要な情報のみ

# 監視・ヘルスチェック（検証用）
monitoring:
  health_check:
    enabled: true
    interval_seconds: 15
    timeout_seconds: 5
    
  performance:
    enabled: true
    metrics_interval: 120       # 2分間隔
    
  # 検証用メトリクス
  validation_metrics:
    enabled: true
    track_latency: true
    track_slippage: true
    track_fill_rate: true
    report_interval_hours: 6    # 6時間ごとレポート

# 検証用目標指標
targets:
  # 本番移行条件
  monthly_profit_target: 8000   # 月間8,000円利益目標
  max_monthly_trades: 400       # 月間最大400回
  target_win_rate: 0.55         # 勝率55%目標
  target_sharpe_ratio: 0.9      # シャープレシオ0.9目標
  
  evaluation_period_days: 7     # 7日間評価
  min_trades_for_evaluation: 30 # 最低30取引

# セキュリティ設定（検証用）
security:
  api_key_rotation_days: 30
  max_api_calls_per_hour: 1200
  emergency_contacts:
    - "validation@example.com"
  
  # 検証用安全装置
  safety_measures:
    max_total_loss_jpy: 5000    # 総損失5,000円で停止
    max_daily_trades: 20        # 1日最大20取引
    circuit_breaker_enabled: true # サーキットブレーカー有効
    
# 検証完了条件
completion_criteria:
  # 自動評価条件
  auto_evaluation: true
  evaluation_frequency_hours: 24  # 24時間ごと評価
  
  # 合格条件
  success_conditions:
    min_total_trades: 30        # 最低30取引
    min_win_rate: 0.55          # 勝率55%
    max_drawdown: 0.08          # ドローダウン8%以内
    min_profit_jpy: 2000        # 2,000円以上利益
    no_major_errors: true       # 重大エラーなし
  
  # 次段階移行条件
  next_stage_conditions:
    stage_10percent: "validation_passed"   # 検証合格で10%段階
    stage_50percent: "10percent_success"   # 10%成功で50%段階
    stage_production: "50percent_success"  # 50%成功で本番