backtest:
  starting_balance: 10000.0
  slippage_rate: 0.001

# 軽量データ設定（高速テスト用）
data:
  exchange: bitbank
  symbol: BTC/JPY
  timeframe: 1h
  limit: 100  # 軽量化
  since_hours: 120  # 5日分のみ
  
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000

# 積極的ML設定
ml:
  model_type: lgbm
  confidence_threshold: 0.40  # 大幅緩和
  
  ensemble:
    enabled: true
    method: trading_stacking
    confidence_threshold: 0.40  # 大幅緩和
    models: ["lgbm", "xgb", "rf"]
    
  # 基本特徴量のみ（高速化）
  extra_features: [
    "ema_20", "rsi_14", "macd", "atr_14", "volume_ratio"
  ]

# 積極的戦略設定
strategy:
  name: multi_timeframe_ensemble
  confidence_threshold: 0.40  # 大幅緩和
  
  params:
    threshold: 0.003  # 0.3%で取引
    threshold_bounds: [0.001, 0.03]
    atr_multiplier: 0.7  # 高感度
    max_volatility_adj: 0.07
    volatility_adjustment: true
    model_path: /app/models/production/model.pkl

# リスク管理（適度に緩和）
risk:
  risk_per_trade: 0.02  # 2%に増加
  kelly_criterion:
    enabled: true
    max_fraction: 0.05

# ライブ設定
live:
  mode: backtest
  starting_balance: 10000.0
  
# ログ設定
logging:
  level: INFO