# =============================================================================
# ファイル名: config/bitbank_production_jpy_realistic.yml
# 説明:
# Bitbank本番運用JPY建て設定（現実的パラメータ調整版）
# - 79.7%勝率ベースライン設定をBitbank本番環境に最適化
# - JPY建て表記・Bitbank手数料構造反映
# - より現実的なスリッページ・リスク設定
# =============================================================================

# ----------------------------------------------------------------------
# データ取得設定（Bitbank本番・JPY建て）
# ----------------------------------------------------------------------
data:
  exchange: bitbank
  symbol: BTC/JPY  # JPY建て取引
  timeframe: 1h

  # ------ Bitbank 本番オプション ------
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 1000  # Bitbank API制限対応
  # --------------------------------------

  # 学習用データ取得範囲
  since: "2024-01-01T00:00:00Z"  # より長期間の学習データ
  limit: 8000  # 約11ヶ月分の1時間足データ
  paginate: true
  per_page: 200  # Bitbank制限に合わせて保守的に

# ----------------------------------------------------------------------
# 戦略設定 ―― 79.7%勝率ベースライン移植版
# ----------------------------------------------------------------------
strategy:
  type: single
  name: ml
  params:
    model_path: model.pkl
    threshold: 0.05  # ベースライン設定維持
    
    # 動的閾値調整（ベースライン）
    atr_multiplier: 0.5
    volatility_adjustment: true
    threshold_bounds: [0.01, 0.25]
    
    thresholds_to_test:
      - 0.02
      - 0.05
      - 0.08
      - 0.10
      - 0.15

# ----------------------------------------------------------------------
# リスク管理（Bitbank現実対応）
# ----------------------------------------------------------------------
risk:
  risk_per_trade: 0.015  # 2% → 1.5%（本番では保守的）
  stop_atr_mult: 1.6     # 1.5 → 1.6（JPY建て流動性考慮）
  dynamic_position_sizing:
    enabled: true
    formula: linear  # 本番では安定性重視
  
  # Kelly基準（本番調整）
  kelly_criterion:
    enabled: true
    lookback_window: 30  # ベースライン維持
    max_fraction: 0.15   # 20% → 15%（本番リスク軽減）
    min_trades_required: 10

# ----------------------------------------------------------------------
# バックテスト（JPY建て・50万円想定）
# ----------------------------------------------------------------------
backtest:
  starting_balance: 500000.0  # 50万円（JPY）
  slippage_rate: 0.004  # 0.001 → 0.004（Bitbank現実的）
  commission_rate: 0.0012  # Bitbank現物平均手数料
  trade_log_csv: "./results/trade_log_bitbank_jpy.csv"
  aggregate_out_prefix: "./results/aggregate_bitbank_jpy"

# ----------------------------------------------------------------------
# ウォークフォワード分割（ベースライン維持）
# ----------------------------------------------------------------------
walk_forward:
  train_window: 1000     # ベースライン設定
  test_window: 168       # 1週間テスト
  step: 168              # 1週間スライド

# ----------------------------------------------------------------------
# 機械学習（90特徴量対応・ベースライン移植）
# ----------------------------------------------------------------------
ml:
  feat_period: 14
  lags: [1,2,3,4,5,6,7,8,9,10,11,12]
  rolling_window: 20
  horizon: 5
  target_type: classification
  model_type: lgbm

  # VIX統合設定（ベースライン）
  vix_integration:
    enabled: true
    risk_off_threshold: 25
    panic_threshold: 35
    spike_multiplier: 2.0

  # アンサンブルモデル設定（ベースライン）
  ensemble:
    enabled: true
    method: stacking
    weights: [0.4, 0.3, 0.3]
    
    base_models:
      - type: lgbm
        n_estimators: 89
        max_depth: 9
        learning_rate: 0.09558059446177633
        bagging_fraction: 0.6
        lambda_l1: 1.0
        lambda_l2: 0.5
      - type: rf
        n_estimators: 100
        max_depth: 8
        min_samples_split: 5
        min_samples_leaf: 2
      - type: xgb
        n_estimators: 100
        max_depth: 7
        learning_rate: 0.1
        subsample: 0.8
        colsample_bytree: 0.8

  # ==========================
  # 90特徴量完全対応システム（ベースライン移植）
  # 
  # 実際の生成特徴量数に基づく正確な設定
  # - 基本テクニカル: 6個
  # - 高度テクニカル: 18個（複数サブ特徴量含む）
  # - マクロ経済統合: 51個（VIX・DXY・Fear&Greed・Funding）
  # - 時間・シグナル: 4個
  # - 追加移動平均: 8個
  # 合計: 約90特徴量
  # ==========================
  extra_features:
    # === 基本テクニカル指標（6個） ===
    - rsi_14      # RSI(14)
    - macd        # MACD（3カラム: macd, macd_signal, macd_hist）
    - rci_9       # RCI(9)
    - volume_zscore  # 出来高Zスコア
    - sma_200     # 長期移動平均
    - ema_50      # 中期移動平均
    
    # === 高度テクニカル指標（18個生成） ===
    - stoch       # ストキャスティクス（2カラム: stoch_k, stoch_d）
    - bb          # ボリンジャーバンド（5カラム: bb_upper, bb_middle, bb_lower, bb_percent, bb_width）
    - adx         # ADX（3カラム: adx, di_plus, di_minus）
    - willr       # Williams %R
    - cmf         # チャイキンマネーフロー
    - fisher      # フィッシャートランスフォーム（2カラム: fisher, fisher_signal）
    
    # === マクロ経済統合（51個生成） ===
    - vix         # VIX恐怖指数（6特徴量）
    - dxy         # DXY・金利（10特徴量）
    - fear_greed  # Fear&Greed（18特徴量 = 14基本 + 4相関）
    - funding     # Funding Rate・OI（17特徴量）
    
    # === 時間・シグナル特徴量（4個） ===
    - day_of_week
    - hour_of_day
    - mochipoyo_long_signal
    - mochipoyo_short_signal
    
    # === 追加移動平均（8個） ===
    - sma_50
    - sma_100
    - ema_12
    - ema_26
    - sma_20
    - ema_20
    - sma_10
    - ema_10

  # Optuna設定（ベースライン）
  optuna:
    n_trials: 10
    timeout: 300
    direction: maximize
    sampler:
      name: TPESampler
    pruner:
      name: MedianPruner
      n_startup_trials: 5
      n_warmup_steps: 10
      interval_steps: 1

  # モデルパラメータ（ベースライン）
  model_params:
    n_estimators: 89
    max_depth: 9
    learning_rate: 0.09558059446177633
    bagging_fraction: 0.6
    lambda_l1: 1.0
    lambda_l2: 0.5

  # ハイパーパラメータ探索範囲
  model_params_search_space:
    max_depth:        [3,6,9,12,15]
    learning_rate:    [0.001,0.01,0.05,0.1]
    feature_fraction: [0.6,0.8,1.0]
    bagging_fraction: [0.6,0.8,1.0]
    lambda_l1:        [0.0,0.1,0.5,1.0]
    lambda_l2:        [0.0,0.1,0.5,1.0]

  # モデルキャリブレーション
  calibration:
    method: sigmoid
    cv: prefit

# ----------------------------------------------------------------------
# ライブトレード設定（Bitbank本番対応）
# ----------------------------------------------------------------------
live:
  mode: paper  # 初期はペーパートレードで検証
  
  # 取引パラメータ（JPY建て調整）
  trade_interval: 60  # 1時間間隔
  min_order_size: 0.001  # Bitbank最小注文量
  max_daily_trades: 8   # 日本市場時間考慮で抑制
  emergency_stop_loss: 0.04  # 4%（JPY建てボラティリティ考慮）
  
  # 日本市場時間最適化
  active_hours: [9, 15]  # JST 9:00-15:00 メイン活動時間
  night_mode_reduced_risk: true  # 夜間リスク軽減
  
  # ログ・状態管理
  log_level: INFO
  log_trades: true
  status_file: status_bitbank_jpy_production.json

# ----------------------------------------------------------------------
# 監視・アラート設定（JPY建て対応）
# ----------------------------------------------------------------------
monitoring:
  enabled: true
  check_interval: 30
  
  # JPY建てアラート基準
  alerts:
    - type: daily_profit
      threshold: 15000    # 日次利益1.5万円以上で通知
      action: notify
    - type: daily_loss
      threshold: 10000    # 日次損失1万円でアラート
      action: reduce_risk
    - type: win_rate
      threshold: 0.65     # 勝率65%以下でモデル見直し
      action: model_refresh
    - type: position_size
      threshold: 100000   # ポジション10万円以上で監視強化
      action: alert

# ----------------------------------------------------------------------
# Bitbank特有の設定
# ----------------------------------------------------------------------
bitbank_specific:
  # 注文タイプ優先度
  preferred_order_type: "limit"  # 指値注文優先
  
  # 日本円建て資金管理
  jpy_balance_management:
    reserve_ratio: 0.1  # 10%は現金として保持
    rebalance_threshold: 0.05  # 5%以上乖離で リバランス
  
  # 税務対応
  tax_calculation:
    method: "moving_average"  # 移動平均法
    reporting_currency: "JPY"
    
# ----------------------------------------------------------------------
# 期待効果（JPY建て・Bitbank現実対応版）
# ----------------------------------------------------------------------
# 79.7%勝率ベースラインからの現実調整:
# 
# 調整要因:
# - スリッページ: 0.1% → 0.4% (+0.3%)
# - 手数料: 無視 → 0.12% (+0.12%)  
# - リスク軽減: 2% → 1.5% (-25%ポジション)
# - 流動性差: Bybit → Bitbank (若干の不利)
# 
# 予想調整後パフォーマンス:
# - 勝率: 79.7% → 75-78% (高水準維持)
# - 年間収益: 25% → 18-22% (現実的水準)
# - シャープレシオ: 16.13 → 8-12 (依然として優秀)
# - 50万円運用例: 年間590-610万円 (+18-22%)
# 
# 現実的な期待値:
# - 保守ケース: 50万円 → 55-58万円 (+10-16%)
# - 標準ケース: 50万円 → 59-61万円 (+18-22%)  
# - 楽観ケース: 50万円 → 62-65万円 (+24-30%)
# ----------------------------------------------------------------------