backtest:
  aggregate_out_prefix: ./results/aggregate_125features_6month
  commission_rate: 0.0012
  maker_commission_rate: -0.0002
  slippage_rate: 0.0012
  starting_balance: 10000.0
  trade_log_csv: ./results/trade_log_125features_6month_analysis.csv
cloud_run_optimization:
  batch_processing: true
  cpu_limit: 1000m
  execution_timeout: 300
  logging:
    level: INFO
    reduce_verbose: true
    structured: true
  memory_limit: 2Gi
data:
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false
  exchange: bitbank
  exponential_backoff: true
  fetch_retries: 3
  limit: 400
  paginate: true
  per_page: 200
  since_hours: 96
  symbol: BTC/JPY
  timeframe: 1h
  weekend_data: true
  weekend_extension_hours: 72
external_data_retry:
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 300
  exponential_backoff: true
  max_retries: 3
  retry_delay: 2
live:
  bitbank_settings:
    max_retries: 3
    min_btc_amount: 0.0001
    retry_delay: 5
  margin_trading:
    enabled: true
    force_margin_mode: true
    leverage: 1.0
    position_type: both
    verify_margin_status: true
  max_order_size: 0.0005
  min_order_size: 0.0001
  mode: backtest
  starting_balance: 10000.0
  trade_interval: 60
ml:
  ensemble:
    confidence_threshold: 0.6
    enabled: true
    method: trading_stacking
    model_weights:
    - 0.5
    - 0.3
    - 0.2
    models:
    - lgbm
    - xgb
    - rf
    risk_adjustment: true
  external_data:
    cache_enabled: false
    enabled: false
    fallback_enabled: true
    funding:
      enabled: false
      exchanges:
      - binance
      fallback_rate: 0.0001
      symbol: BTC/USDT
    include_in_features: false
    macro:
      enabled: false
      fallback_values:
        dxy: 103.0
        us10y: 4.5
        us2y: 4.8
      symbols:
        dxy: DX-Y.NYB
        us10y: ^TNX
        us2y: ^IRX
    vix:
      enabled: false
      fallback_level: 20.0
      symbol: ^VIX
      timeframe: 1d
  extra_features:
  - close_lag_1
  - close_lag_2
  - close_lag_3
  - close_lag_4
  - close_lag_5
  - volume_lag_1
  - volume_lag_2
  - volume_lag_3
  - volume_lag_4
  - volume_lag_5
  - returns_1
  - returns_2
  - returns_3
  - returns_5
  - returns_10
  - log_returns_1
  - log_returns_2
  - log_returns_3
  - log_returns_5
  - log_returns_10
  - sma_5
  - sma_10
  - sma_20
  - sma_50
  - sma_100
  - sma_200
  - ema_5
  - ema_10
  - ema_20
  - ema_50
  - ema_100
  - ema_200
  - price_position_20
  - price_position_50
  - price_vs_sma20
  - bb_position
  - intraday_position
  - bb_upper
  - bb_middle
  - bb_lower
  - bb_width
  - bb_squeeze
  - rsi_14
  - rsi_7
  - rsi_21
  - rsi_oversold
  - rsi_overbought
  - macd
  - macd_signal
  - macd_hist
  - macd_cross_up
  - macd_cross_down
  - stoch_k
  - stoch_d
  - stoch_oversold
  - stoch_overbought
  - atr_14
  - atr_7
  - atr_21
  - volatility_20
  - volatility_50
  - high_low_ratio
  - true_range
  - volatility_ratio
  - volume_sma_20
  - volume_ratio
  - volume_trend
  - vwap
  - vwap_distance
  - obv
  - obv_sma
  - cmf
  - mfi
  - ad_line
  - adx_14
  - plus_di
  - minus_di
  - trend_strength
  - trend_direction
  - cci_20
  - williams_r
  - ultimate_oscillator
  - support_distance
  - resistance_distance
  - support_strength
  - volume_breakout
  - price_breakout_up
  - price_breakout_down
  - doji
  - hammer
  - engulfing
  - pinbar
  - skewness_20
  - kurtosis_20
  - zscore
  - mean_reversion_20
  - mean_reversion_50
  - hour
  - day_of_week
  - is_weekend
  - is_asian_session
  - is_european_session
  - is_us_session
  - momentum_14
  - roc_14
  - srsi_k
  - srsi_d
  - trix
  - kst
  - cmo
  - ppo
  - ppo_signal
  - ppo_hist
  - ift_rsi
  - cti
  - wt1
  - wt2
  - ui
  - tci
  - ap
  - hlc3
  - ohlc4
  - typical_price
  - weighted_close
  - dpo
  feat_period: 14
  horizon: 5
  lags:
  - 1
  - 2
  - 3
  model_type: lgbm
  rolling_window: 10
  target_type: classification
monitoring:
  check_interval: 300
  enabled: true
  metrics:
  - total_return
  - sharpe_ratio
  - max_drawdown
  - win_rate
  - profit_factor
  - trade_count
quality_monitoring:
  default_threshold: 0.3
  emergency_stop_threshold: 0.35
  enabled: true
  high_quality_mode:
    confidence_boost: 0.0
    position_size_reduction: 1.0
    stop_loss_tightening: 1.0
  low_quality_mode:
    confidence_boost: 0.1
    position_size_reduction: 0.5
    stop_loss_tightening: 0.8
  max_threshold: 0.8
  medium_quality_mode:
    confidence_boost: 0.03
    position_size_reduction: 0.8
    stop_loss_tightening: 0.95
  target_threshold: 0.6
risk:
  atr_period: 20
  kelly_criterion:
    enabled: true
    max_fraction: 0.05
  risk_per_trade: 0.005
  stop_atr_mult: 1.2
strategy:
  name: ml
  params:
    atr_multiplier: 0.5
    model_path: models/production/model.pkl
    threshold: 0.02
    threshold_bounds:
    - 0.01
    - 0.25
    volatility_adjustment: true
  type: single
walk_forward:
  step: 24
  test_window: 120
  train_window: 360
