backtest:
  commission: 0.001
  end_date: '2024-12-31'
  evaluation_metrics:
  - total_return
  - sharpe_ratio
  - win_rate
  - max_drawdown
  - profit_factor
  - calmar_ratio
  - sortino_ratio
  - ensemble_confidence
  - model_agreement
  - prediction_stability
  initial_balance: 1000000
  slippage: 0.0005
  start_date: '2024-01-01'
data:
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false
  exchange: bitbank
  exponential_backoff: true
  fetch_retries: 3
  limit: 400
  paginate: true
  per_page: 200
  since_hours: 96
  symbol: BTC/JPY
  timeframe: 1h
  weekend_data: true
  weekend_extension_hours: 72
logging:
  ensemble_tracking: true
  level: INFO
  performance_metrics: true
  risk_metrics: true
  trading_decisions: true
ml:
  dynamic_threshold:
    base_threshold: 0.45
    enabled: true
    performance_adjustment: true
    vix_adjustment: true
    vix_levels:
      extreme_vix:
        adjustment: 0.2
        threshold: 50
      high_vix:
        adjustment: 0.1
        threshold: 35
      low_vix:
        adjustment: -0.05
        threshold: 15
      medium_vix:
        adjustment: 0.0
        threshold: 25
    volatility_adjustment: true
  ensemble:
    base_models:
    - bagging_fraction: 0.8
      feature_fraction: 0.9
      lambda_l1: 0.1
      lambda_l2: 0.1
      learning_rate: 0.05
      max_depth: 8
      n_estimators: 200
      type: lgbm
    - colsample_bytree: 0.8
      learning_rate: 0.05
      max_depth: 6
      n_estimators: 200
      reg_alpha: 0.1
      reg_lambda: 0.1
      subsample: 0.8
      type: xgb
    - max_depth: 10
      max_features: sqrt
      min_samples_leaf: 2
      min_samples_split: 5
      n_estimators: 150
      type: rf
    confidence_threshold: 0.65
    enabled: true
    meta_model:
      C: 1.0
      class_weight: balanced
      max_iter: 1000
      type: lr
    method: trading_stacking
    risk_adjustment: true
    trading_metrics:
      max_drawdown: -0.2
      profit_factor: 0.1
      sharpe_ratio: 0.4
      win_rate: 0.3
  extra_features:
  - vix
  - vix_change
  - vix_zscore
  - vix_spike
  - fear_level
  - volatility_regime
  - dxy
  - dxy_change
  - us_10y
  - yield_curve
  - real_rates
  - dollar_strength
  - fed_funds_rate
  - treasury_volatility
  - currency_momentum
  - rate_expectations
  - fear_greed
  - fear_greed_ma
  - fear_greed_change
  - extreme_fear
  - extreme_greed
  - sentiment_regime
  - sentiment_divergence
  - social_sentiment
  - options_sentiment
  - momentum_sentiment
  - volume_sentiment
  - breadth_sentiment
  - volatility_sentiment
  - funding
  - funding_ma
  - funding_change
  - funding_extreme
  - oi_change
  - oi_volume_ratio
  - leverage_ratio
  - long_short_ratio
  - liquidation_risk
  - perpetual_basis
  - futures_basis
  - options_flow
  - institutional_flow
  - retail_sentiment
  - whale_activity
  - exchange_flows
  - stablecoin_flows
  - rsi_14
  - rsi_7
  - rsi_21
  - macd
  - macd_signal
  - macd_histogram
  - bb_percent
  - bb_width
  - sma_20
  - sma_50
  - sma_200
  - ema_12
  - ema_26
  - ema_50
  - adx
  - cci
  - williams_r
  - stoch_k
  - stoch_d
  - momentum_14
  - day_of_week
  - hour_of_day
  - mochipoyo_long_signal
  - mochipoyo_short_signal
  - price_change_1h
  - price_change_4h
  - price_change_24h
  - volume_change_1h
  - volume_change_24h
  - volume_zscore
  - volatility_1h
  - volatility_24h
  - support_resistance
  - trend_strength
  - breakout_signal
  - reversal_signal
  - fibonacci_level
  - pivot_points
  - bollinger_squeeze
  - volume_profile
  - order_flow
  - market_microstructure
  - cross_asset_correlation
  - sector_rotation
  - macro_regime
  - central_bank_policy
  - economic_surprises
  - earnings_season
  - options_expiry
  - futures_rollover
  - seasonal_patterns
  - anomaly_detection
  - regime_change
  - tail_risk
  - skewness
  feat_period: 14
  horizon: 5
  lags:
  - 1
  - 2
  - 3
  rolling_window: 20
  target_type: classification
risk:
  position_sizing:
    base_size: 0.1
    confidence_scaling: true
    max_size: 0.15
    method: kelly_criterion
    risk_adjustment: true
  stop_loss:
    atr_multiplier: 2.0
    enabled: true
    max_loss: 0.02
  take_profit:
    enabled: true
    partial_sizes:
    - 0.3
    - 0.4
    - 0.3
    profit_targets:
    - 0.015
    - 0.03
    - 0.05
strategy:
  name: ensemble_ml_strategy
  params:
    atr_multiplier: 0.5
    confidence_filter: 0.65
    partial_profit_levels:
    - 0.3
    - 0.5
    threshold_bounds:
    - 0.3
    - 0.8
    trailing_stop_enabled: true
    vix_panic_threshold: 35
    vix_risk_off_threshold: 25
    vix_spike_multiplier: 2.0
    volatility_adjustment: true
