# 検証用設定ファイル（マルチタイムフレーム×アンサンブル学習）
# 本番前テスト・パフォーマンス検証・安全性確認用
# 本番稼働前にこの設定で検証完了後、production.ymlに上書き

data:
  exchange: bitbank
  symbol: BTC/JPY
  timeframe: 1h  # ベースタイムフレーム（マルチタイムフレーム変換用）
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 2500  # 検証用：保守的設定（本番2000ms）
    
  # 検証用データ取得設定（軽量化）
  limit: 50        # 本番100→50に削減（検証効率化）
  paginate: true
  per_page: 10     # 本番20→10に削減（API負荷軽減）
  
  # マルチタイムフレーム対応データ設定
  multi_timeframe_data:
    base_timeframe: "1h"  
    target_timeframes:    
      15m:
        method: "interpolation"  
        min_points: 25      # 本番50→25（軽量化）
      1h:
        method: "direct"         
        min_points: 50      # 本番100→50（軽量化）
      4h:
        method: "aggregation"    
        min_points: 12      # 本番25→12（軽量化）

strategy:
  type: multi_timeframe_ensemble
  name: multi_timeframe_ensemble_test  # 検証用識別
  params:
    model_path: /app/models/validation/model_test.pkl  # 検証用モデルパス
    threshold: 0.08  # 本番0.05→0.08（保守的）

# マルチタイムフレーム設定（検証用調整）
multi_timeframe:
  timeframes: ["15m", "1h", "4h"]
  weights: [0.25, 0.5, 0.25]  # 15分足25%, 1時間足50%, 4時間足25%（調整版）
  data_sync_enabled: true
  missing_data_tolerance: 0.15  # 本番0.1→0.15（許容範囲拡大）
  timeframe_consensus_threshold: 0.5  # 本番0.6→0.5（検証用緩和）

# 検証用リスク設定（保守的）
risk:
  risk_per_trade: 0.002  # 本番0.005→0.002（リスク削減）
  stop_atr_mult: 1.5     # 本番1.2→1.5（ストップ幅拡大）
  kelly_criterion:
    enabled: true
    max_fraction: 0.02   # 本番0.05→0.02（資金制限）
  atr_period: 7

# 検証用ライブ設定
live:
  mode: paper  # 検証用：ペーパートレード
  trade_interval: 120  # 本番60→120秒（頻度削減）
  min_order_size: 0.00005  # 本番0.0001→半分
  max_order_size: 0.0001   # 本番0.0005→1/5
  starting_balance: 1000.0 # 検証用少額
  margin_trading:
    enabled: false  # 検証段階では無効
    leverage: 1.0
    position_type: "long"  # 検証用：ロングのみ
  
  bitbank_settings:
    min_btc_amount: 0.00005  # 検証用削減
    max_retries: 5     # 本番3→5（安定性重視）
    retry_delay: 8     # 本番5→8秒（保守的）

# 151特徴量軽量版ML設定（検証用高速化）
ml:
  feat_period: 10    # 本番14→10（高速化）
  lags: [1,2,3]      # 本番[1,2,3,4,5]→[1,2,3]（削減）
  rolling_window: 15 # 本番20→15（削減）
  horizon: 3         # 本番5→3（削減）
  target_type: classification
  model_type: lgbm
  
  # アンサンブル学習設定（軽量化）
  ensemble:
    enabled: true
    method: trading_stacking
    confidence_threshold: 0.6  # 本番0.65→0.6（緩和）
    risk_adjustment: true
    models: ["lgbm", "rf"]     # 本番3モデル→2モデル（高速化）
    model_weights: [0.7, 0.3]  # LGBM70%, RF30%
    
  # 検証用特徴量設定（軽量化）
  extra_features:
    # 基本テクニカル特徴量（必須のみ）
    - rsi_14
    - macd
    - sma_50
    - sma_200
    - ema_12
    - ema_26
    - stoch
    - adx
    
    # 外部データ特徴量（軽量版）
    - vix          # VIX恐怖指数
    - dxy          # ドル指数・金利
    - fear_greed   # Fear&Greed指数（軽量）
    
    # 高度特徴量（選択的）
    - volatility_regime    # ボラティリティレジーム
    - momentum_signals     # モメンタム信号
    
  # 外部データ設定（検証用）
  external_data:
    enabled: true
    cache_enabled: true
    fallback_enabled: true
    
    vix:
      enabled: true
      symbol: "^VIX"
      timeframe: "1d"
      fallback_level: 20.0
      sources: ["yahoo"]  # 検証用：Yahooのみ
      quality_threshold: 0.6
      cache_hours: 24
      
    macro:
      enabled: true
      symbols:
        dxy: "DX-Y.NYB"
        us10y: "^TNX"
      fallback_values:
        dxy: 103.0
        us10y: 4.5
      sources: ["yahoo"]
      quality_threshold: 0.7
      cache_hours: 12
        
    fear_greed:
      enabled: true
      api_url: "https://api.alternative.me/fng/"
      fallback_index: 50
      sources: ["alternative_me"]  # データソース追加
      quality_threshold: 0.5
      cache_hours: 1
      
    funding:
      enabled: false  # 検証段階では無効（高速化）

# 外部データリトライ設定（保守的）
external_data_retry:
  max_retries: 5      # 本番3→5
  retry_delay: 3      # 本番2→3秒
  exponential_backoff: true
  circuit_breaker:
    enabled: true
    failure_threshold: 3  # 本番5→3（早期検出）
    recovery_timeout: 600 # 本番300→600秒（長期回復）

# 品質監視設定（検証用緩和）
quality_monitoring:
  enabled: true
  default_threshold: 0.4       # 本番0.3→0.4（緩和）
  emergency_stop_threshold: 0.6 # 本番0.5→0.6（緩和）
  
# バックテスト設定
backtest:
  starting_balance: 1000.0  # 検証用少額
  slippage_rate: 0.002      # 本番0.001→0.002（現実的）

# ログ設定（検証用詳細化）
logging:
  level: DEBUG  # 本番INFO→DEBUG
  file: /app/logs/bitbank_validation_test.log
  rotation: daily
  retention: 3  # 本番7→3日（容量節約）

# Bitbank手数料最適化設定（検証用）
bitbank:
  fee_optimization:
    enabled: false  # 検証段階では無効
    maker_fee: -0.0002  
    taker_fee: 0.0012   
    prefer_maker: true
    min_profit_after_fees: 0.005  # 本番0.002→0.005（保守的）
    
  order_management:
    max_open_orders: 10  # 本番30→10（制限）
    rate_limit:
      get_requests: 5    # 本番10→5（保守的）
      post_requests: 3   # 本番6→3（保守的）
    queue_enabled: true
    
  day_trading:
    enabled: false  # 検証段階では無効

# 検証用メタデータ
validation:
  purpose: "pre_production_testing"
  created_date: "2025-07-21"
  target_production_config: "config/production/production.yml"
  upgrade_strategy: "validated_overwrite"
  test_duration_hours: 24
  success_criteria:
    - "processing_time < 4.0s"
    - "data_quality > 60%"
    - "feature_count == 151"
    - "no_critical_errors"