# 取引実行可能版 - production.yml基準の微調整設定
# 2025年8月3日作成 - 保守性向上・本番昇格候補

backtest:
  starting_balance: 10000.0
  slippage_rate: 0.001

# Walk Forward設定（シンプルバックテスト用に無効化）
walk_forward:
  enabled: false
  step: 5
  test_window: 10
  train_window: 20

# 十分なデータ設定
data:
  exchange: bitbank
  symbol: BTC/JPY
  timeframe: 1h
  limit: 200          # 実装特徴量に合わせて軽量化
  since_hours: 72     # 3日分で安定動作
  
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false

# 軽量ML設定（実装済み特徴量のみ）
ml:
  model_type: lgbm
  confidence_threshold: 0.35    # 取引機会確保
  feat_period: 14
  rolling_window: 10
  horizon: 5
  lags: [1, 2, 3]
  target_type: classification
  
  ensemble:
    enabled: true
    method: trading_stacking
    confidence_threshold: 0.35  # 取引機会確保
    models: ["lgbm", "xgb", "rf"]
    model_weights: [0.5, 0.3, 0.2]
    risk_adjustment: true
    
  # 実装済み基本特徴量のみ（92個→12個に削減）
  extra_features: [
    # 基本技術指標（実装済み）
    "ema_20", "ema_50", "rsi_14", "macd", "atr_14", "volatility_20",
    # 出来高・価格系（実装済み）
    "volume_ratio", "cmf", "day_of_week",
    # 統計系（実装済み）
    "zscore", "close_std_10", "momentum_14"
  ]

# 取引実行保証戦略設定
strategy:
  name: multi_timeframe_ensemble
  confidence_threshold: 0.35    # 実際の予測値に合わせて調整
  
  params:
    threshold: 0.002             # 0.2%で取引実行
    threshold_bounds: [0.001, 0.02]
    atr_multiplier: 0.8          # 高感度
    max_volatility_adj: 0.08
    volatility_adjustment: true
    model_path: /app/models/production/model.pkl

# リスク管理（適度に緩和）
risk:
  risk_per_trade: 0.015          # 1.5%
  atr_period: 20
  stop_atr_mult: 1.2
  kelly_criterion:
    enabled: true
    max_fraction: 0.04

# マルチタイムフレーム（データ要件緩和）
multi_timeframe:
  timeframes: ["15m", "1h", "4h"]
  weights: [0.3, 0.5, 0.2]
  data_quality_threshold: 0.3    # 大幅緩和
  timeframe_consensus_threshold: 0.4  # 大幅緩和
  missing_data_tolerance: 0.3    # 大幅緩和

# 品質監視（緩和）
quality_monitoring:
  enabled: true
  default_threshold: 0.15         # 大幅緩和
  emergency_stop_threshold: 0.2   # 大幅緩和

# Bitbank設定
bitbank:
  fee_optimization:
    enabled: true
    maker_fee: -0.0002
    taker_fee: 0.0012
    prefer_maker: true
    min_profit_after_fees: 0.001  # 緩和
    
  order_management:
    max_open_orders: 30
    queue_enabled: true

# ライブ設定
live:
  mode: backtest
  starting_balance: 10000.0
  trade_interval: 60
  min_order_size: 0.0001
  max_order_size: 0.001          # 増加
  
  margin_trading:
    enabled: true
    leverage: 1.0
    position_type: both

# ログ設定
logging:
  level: INFO
  file: /app/logs/production_trading_enabled.log