backtest:
  slippage_rate: 0.001
  starting_balance: 10000.0
bitbank:
  fee_optimization:
    enabled: true
    maker_fee: -0.0002
    prefer_maker: true
    taker_fee: 0.0012
data:
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false
  exchange: bitbank
  exponential_backoff: true
  fetch_retries: 3
  limit: 400
  paginate: true
  per_page: 200
  since_hours: 96
  symbol: BTC/JPY
  timeframe: 1h
  weekend_data: true
  weekend_extension_hours: 72
ml:
  confidence_threshold: 0.35
  extra_features:
  - open
  - high
  - low
  - close
  - volume
  - rsi_14
  - sma_20
  - sma_50
  - ema_20
  - ema_50
  - atr_14
  - macd
  - volatility_20
  - volume_sma_20
  - volume_ratio
  - high_low_ratio
  - true_range
  - trend_strength
  - hour
  - day_of_week
  - momentum_14
  feat_period: 14
  horizon: 5
  lags:
  - 1
  - 2
  - 3
  model_type: lgbm
  rolling_window: 10
  target_type: classification
risk:
  atr_period: 14
  kelly_criterion:
    enabled: true
    max_fraction: 0.02
  risk_per_trade: 0.01
  stop_atr_mult: 1.5
strategy:
  name: ml
  params:
    atr_multiplier: 0.3
    model_path: models/production/model.pkl
    threshold: 0.05
    threshold_bounds:
    - 0.02
    - 0.15
    volatility_adjustment: true
  type: single
walk_forward:
  step: 6
  test_window: 24
  train_window: 200
