backtest:
  aggregate_out_prefix: ./results/robust_model_backtest
  commission_rate: 0.0005
  slippage_rate: 0.001
  starting_balance: 10000.0
  trade_log_csv: ./results/robust_model_trade_log.csv
data:
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false
  exchange: bitbank
  exponential_backoff: true
  fetch_retries: 3
  limit: 400
  paginate: true
  per_page: 200
  since_hours: 96
  symbol: BTC/JPY
  timeframe: 1h
  weekend_data: true
  weekend_extension_hours: 72
ml:
  extra_features:
  - returns_2
  - returns_3
  - returns_5
  - returns_10
  - log_returns_2
  - log_returns_3
  - log_returns_5
  - log_returns_10
  - price_position_20
  - price_position_50
  - price_vs_sma20
  - rsi_14
  - rsi_7
  - rsi_21
  - stoch_k
  - stoch_d
  - stoch_oversold
  - stoch_overbought
  - mfi
  - trend_direction
  - cci_20
  - williams_r
  - ultimate_oscillator
  - support_distance
  - resistance_distance
  - support_strength
  - zscore
  - mean_reversion_20
  - mean_reversion_50
  - roc_10
  feat_period: 14
  horizon: 5
  lags:
  - 1
  - 2
  - 3
  - 4
  - 5
  model_params:
    bagging_fraction: 0.8
    bagging_freq: 5
    boosting_type: gbdt
    feature_fraction: 0.8
    learning_rate: 0.1
    metric: binary_logloss
    min_child_samples: 20
    num_leaves: 31
    objective: binary
    random_state: 42
  model_type: lgbm
  rolling_window: 20
  target_type: classification
monitoring:
  check_interval: 300
  enabled: true
  metrics:
  - total_return
  - sharpe_ratio
  - max_drawdown
  - win_rate
  - profit_factor
  - calmar_ratio
risk:
  dynamic_position_sizing:
    enabled: true
    formula: linear
  kelly_criterion:
    enabled: true
    lookback_window: 50
    max_fraction: 0.25
    min_trades_required: 10
  risk_per_trade: 0.02
  stop_atr_mult: 2.0
strategy:
  name: ml
  params:
    atr_multiplier: 0.3
    model_path: models/production/robust_profitable_model.pkl
    threshold: 0.5
    threshold_bounds:
    - 0.3
    - 0.7
    thresholds_to_test:
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    volatility_adjustment: true
  type: single
walk_forward:
  step: 24
  test_window: 168
  train_window: 720
