backtest:
  slippage_rate: 0.001
  starting_balance: 10000.0
bitbank:
  fee_optimization:
    enabled: true
    maker_fee: -0.0002
    prefer_maker: true
    taker_fee: 0.0012
data:
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false
  exchange: bitbank
  exponential_backoff: true
  fetch_retries: 3
  limit: 400
  paginate: true
  per_page: 200
  since_hours: 96
  symbol: BTC/JPY
  timeframe: 1h
  weekend_data: true
  weekend_extension_hours: 72
ml:
  confidence_threshold: 0.35
  extra_features:
  - close_lag_1
  - close_lag_2
  - close_lag_3
  - close_lag_4
  - close_lag_5
  - volume_lag_1
  - volume_lag_2
  - volume_lag_3
  - volume_lag_4
  - volume_lag_5
  - returns_1
  - returns_2
  - returns_3
  - returns_5
  - returns_10
  - log_returns_1
  - log_returns_2
  - log_returns_3
  - log_returns_5
  - log_returns_10
  - close_mean_10
  - close_std_10
  - sma_5
  - sma_10
  - sma_20
  - sma_50
  - sma_100
  - sma_200
  - ema_5
  - ema_10
  - ema_20
  - ema_50
  - ema_100
  - ema_200
  - price_position_20
  - price_position_50
  - price_vs_sma20
  - bb_position
  - intraday_position
  - bb_upper
  - bb_middle
  - bb_lower
  - bb_width
  - bb_squeeze
  - rsi_14
  - rsi_7
  - rsi_21
  - rsi_oversold
  - rsi_overbought
  - macd
  - macd_signal
  - macd_hist
  - macd_cross_up
  - macd_cross_down
  - stoch_k
  - stoch_d
  - stoch_oversold
  - stoch_overbought
  - atr_14
  - atr_7
  - atr_21
  - volatility_20
  - volatility_50
  - high_low_ratio
  - true_range
  - volatility_ratio
  - volume_sma_20
  - volume_ratio
  - volume_trend
  - vwap
  - vwap_distance
  - obv
  - obv_sma
  - cmf
  - mfi
  - ad_line
  - adx_14
  - plus_di
  - minus_di
  - trend_strength
  - trend_direction
  - cci_20
  - williams_r
  - ultimate_oscillator
  - support_distance
  - resistance_distance
  - support_strength
  - volume_breakout
  - price_breakout_up
  - price_breakout_down
  - doji
  - hammer
  - engulfing
  - pinbar
  - skewness_20
  - kurtosis_20
  - zscore
  - mean_reversion_20
  - mean_reversion_50
  - hour
  - day_of_week
  - is_weekend
  - is_asian_session
  - is_european_session
  - is_us_session
  - roc_10
  - roc_20
  - trix
  - mass_index
  - keltner_upper
  - keltner_lower
  - donchian_upper
  - donchian_lower
  - ichimoku_conv
  - ichimoku_base
  - price_efficiency
  - trend_consistency
  - volume_price_correlation
  - volatility_regime
  - momentum_quality
  - market_phase
  - momentum_14
  feat_period: 14
  horizon: 5
  lags:
  - 1
  - 2
  - 3
  model_type: lgbm
  rolling_window: 10
  target_type: classification
risk:
  atr_period: 20
  kelly_criterion:
    enabled: true
    max_fraction: 0.03
  risk_per_trade: 0.01
  stop_atr_mult: 1.5
strategy:
  name: ml
  params:
    atr_multiplier: 0.3
    model_path: models/production/full_127_features_model.pkl
    threshold: 0.02
    threshold_bounds:
    - 0.01
    - 0.08
    volatility_adjustment: true
  type: single
walk_forward:
  step: 12
  test_window: 48
  train_window: 240
