# バックテスト専用設定ファイル - Phase 19 MLOps統合対応
# 本番と同じ設定・ロジックでのバックテスト実行

# 動作モード（バックテスト専用）
mode: backtest  # バックテストモード専用
# 本番と同等の設定でバックテスト実行し、ローカル検証→GCP成功を保証

# 取引所設定（bitbank信用取引専用）
exchange:
  name: bitbank
  symbol: BTC/JPY          # 信用取引専用通貨ペア
  leverage: 1.0            # 1倍（安全性最優先・実質現物取引相当）
  rate_limit_ms: 35000     # API制限（35秒・安全マージン）
  timeout_ms: 120000       # タイムアウト（2分・本番安全性）
  retries: 5               # リトライ回数増加（本番信頼性）

# 機械学習設定
ml:
  confidence_threshold: 0.65  # 65%（収益性重視・高品質シグナル）
  ensemble_enabled: true      # アンサンブル有効
  models:                     # 使用モデル
    - lgbm
    - xgb
    - rf
  model_weights:              # モデル重み
    - 0.5
    - 0.3
    - 0.2

# リスク管理設定
risk:
  risk_per_trade: 0.01        # 1取引あたりリスク（1%）
  kelly_max_fraction: 0.03    # Kelly基準最大（3%）
  max_drawdown: 0.20          # 最大ドローダウン（20%）
  stop_loss_atr_multiplier: 1.2  # 損切りATR倍率
  consecutive_loss_limit: 5   # 連続損失限界

# データ取得設定
data:
  timeframes:                 # 取得時間軸（2軸構成）
    - 15m
    - 4h
  since_hours: 96            # 取得期間（4日分）
  limit: 100                 # 1回あたり取得数
  cache_enabled: true        # キャッシュ有効

# 特徴量設定（Phase 3最適化版）
features:
  mode: "optimized"          # 12個厳選特徴量
  
  # 基本特徴量
  basic:
    - "close"
    - "volume" 
    - "returns_1"
  
  # テクニカル指標
  technical:
    - "rsi_14"
    - "macd"
    - "atr_14"
    - "bb_position"
    - "ema_20"
    - "ema_50"
  
  # 異常検知
  anomaly:
    - "zscore"
    - "volume_ratio"
    - "market_stress"

# 戦略設定（Phase 4統合版）
strategies:
  enabled:
    - "atr_based"
    - "mochipoy_alert"
    - "multi_timeframe"
    - "fibonacci_retracement"
  
  # 戦略重み（実績ベース）
  weights:
    atr_based: 0.3
    mochipoy_alert: 0.3
    multi_timeframe: 0.25
    fibonacci_retracement: 0.15
  
  # 統合判定
  consensus:
    required_agreement: 0.6  # 60%以上の合意で実行
    confidence_threshold: 0.4

# ログ設定
logging:
  level: DEBUG               # ログレベル（デバッグ用）
  file_enabled: true         # ファイル出力
  discord_enabled: true      # Discord通知
  retention_days: 7          # 保持期間

# Phase 12: 本番運用設定
production:
  min_order_size: 0.0001     # 最小注文サイズ
  max_order_size: 0.001      # 最大注文サイズ
  margin_trading: true       # マージン取引有効
  trade_interval: 60         # 取引間隔（秒）

# Phase 12: 監視システム設定最適化
monitoring:
  health_check:
    enabled: true            # ヘルスチェック有効
    interval_seconds: 30     # チェック間隔
    timeout_seconds: 5       # タイムアウト
    manual_execution: true   # 手動実行対応
  performance:
    enabled: true            # パフォーマンス監視有効
    metrics_interval: 300    # メトリクス収集間隔

# Phase 16-B: セキュリティ設定（GCP統合）
security:
  secret_management: "gcp_secret_manager"  # GCP Secret Manager使用
  workload_identity: true                  # Workload Identity認証