project_id             = "my-crypto-bot-project"
region                 = "asia-northeast1"
artifact_registry_repo = "crypto-bot-repo"
service_name           = "crypto-bot-dev"
image_name             = "crypto-bot"
alert_email            = "s00198532@gmail.com"
github_repo            = "nao-namake/crypto-bot"
project_number         = "11445303925"            # gcloud projects describe で確認
deployer_sa            = "github-deployer@my-crypto-bot-project.iam.gserviceaccount.com"
mode                   = "paper"
feature_mode           = "lite"                   # 軽量版（開発環境用）