# =============================================================================
# ファイル名: config/validation/quick_profit_test.yml
# 説明: 高速利益検証用・1ヶ月バックテスト
# - 99.2%精度モデル検証
# - 短期間・軽量処理
# - 利益改善効果確認
# =============================================================================

# ----------------------------------------------------------------------
# データ取得設定（CSV版）
# ----------------------------------------------------------------------
data:
  exchange: csv
  symbol: BTC/USD
  timeframe: 1h
  csv_path: /Users/nao/Desktop/bot/data/btc_usd_2024_hourly.csv
  
  # 短期間（1ヶ月）
  since: "2024-06-01T00:00:00Z"
  limit: 720  # 1ヶ月（30日 × 24時間）
  
  api_key: null
  api_secret: null
  ccxt_options: {}

# ----------------------------------------------------------------------
# 戦略設定（127特徴量モデル）
# ----------------------------------------------------------------------
strategy:
  type: single
  name: ml
  params:
    model_path: models/production/integrated_127_features_model.pkl
    threshold: 0.05
    atr_multiplier: 0.5
    volatility_adjustment: true
    threshold_bounds: [0.01, 0.25]

# ----------------------------------------------------------------------
# リスク管理（利益最適化）
# ----------------------------------------------------------------------
risk:
  risk_per_trade: 0.02
  stop_atr_mult: 2.0
  dynamic_position_sizing:
    enabled: true
    formula: linear
  
  kelly_criterion:
    enabled: true
    lookback_window: 20  # 短縮
    max_fraction: 0.25
    min_trades_required: 5  # 短縮

# ----------------------------------------------------------------------
# バックテスト設定（高速化）
# ----------------------------------------------------------------------
backtest:
  starting_balance: 10000.0
  slippage_rate: 0.001
  commission_rate: 0.0005
  trade_log_csv: "./results/quick_profit_test_log.csv"
  aggregate_out_prefix: "./results/quick_profit_test"

# ----------------------------------------------------------------------
# ウォークフォワード分割（軽量版）
# ----------------------------------------------------------------------
walk_forward:
  train_window: 240     # 10日間学習
  test_window: 48       # 2日間テスト
  step: 24              # 1日間隔

# ----------------------------------------------------------------------
# 機械学習（軽量化）
# ----------------------------------------------------------------------
ml:
  feat_period: 14
  lags: [1,2,3]  # 短縮
  rolling_window: 10  # 短縮
  horizon: 3     # 短縮
  target_type: classification
  model_type: lgbm

  # 軽量特徴量セット（最重要のみ）
  extra_features:
    - rsi_14
    - macd
    - bb
    - stoch
    - sma_20
    - ema_50
    - volume_ratio
    - atr_14
    - trend_strength
    - momentum_14

  # 軽量パラメータ
  model_params:
    n_estimators: 50  # 短縮
    max_depth: 6      # 短縮
    learning_rate: 0.1
    random_state: 42

# ----------------------------------------------------------------------
# 監視設定（軽量化）
# ----------------------------------------------------------------------
monitoring:
  enabled: false  # 無効化で高速化

# ----------------------------------------------------------------------
# 期待効果: 高速で利益改善効果を確認
# ----------------------------------------------------------------------