# =============================================================================
# ファイル名: config/validation/robust_model_backtest.yml
# 説明:
# 99.2%精度堅牢モデル専用バックテスト設定
# - robust_profitable_model.pkl使用
# - 30選択特徴量対応
# - -¥35,964損失改善検証
# =============================================================================

# ----------------------------------------------------------------------
# データ取得設定（CSV版）
# ----------------------------------------------------------------------
data:
  exchange: csv  # CSV モードを指定
  symbol: BTC/USD  # CSVファイルのシンボル
  timeframe: 1h
  
  # CSV ファイル指定
  csv_path: /Users/nao/Desktop/bot/data/btc_usd_2024_hourly.csv
  
  # 学習用データ期間（1年間フル）
  since: "2024-01-01T00:00:00Z"
  limit: 8760  # 1年分（365日 × 24時間）
  
  # API設定は無効化
  api_key: null
  api_secret: null
  ccxt_options: {}

# ----------------------------------------------------------------------
# 戦略設定（99.2%精度モデル対応）
# ----------------------------------------------------------------------
strategy:
  type: single
  name: ml
  params:
    model_path: models/production/robust_profitable_model.pkl  # 新しい高精度モデル
    threshold: 0.5  # バイナリ分類用閾値
    
    # 動的閾値調整（利益最適化）
    atr_multiplier: 0.3
    volatility_adjustment: true
    threshold_bounds: [0.3, 0.7]
    
    thresholds_to_test:
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      - 0.7

# ----------------------------------------------------------------------
# リスク管理（利益最適化）
# ----------------------------------------------------------------------
risk:
  risk_per_trade: 0.02   # 2%リスク
  stop_atr_mult: 2.0     # ストップロス
  dynamic_position_sizing:
    enabled: true
    formula: linear
  
  # Kelly基準
  kelly_criterion:
    enabled: true
    lookback_window: 50
    max_fraction: 0.25
    min_trades_required: 10

# ----------------------------------------------------------------------
# バックテスト設定（利益検証）
# ----------------------------------------------------------------------
backtest:
  starting_balance: 10000.0   # 1万円
  slippage_rate: 0.001        
  commission_rate: 0.0005     
  trade_log_csv: "./results/robust_model_trade_log.csv"
  aggregate_out_prefix: "./results/robust_model_backtest"

# ----------------------------------------------------------------------
# ウォークフォワード分割
# ----------------------------------------------------------------------
walk_forward:
  train_window: 720      # 30日間学習
  test_window: 168       # 1週間テスト
  step: 24               # 1日間隔

# ----------------------------------------------------------------------
# 機械学習（30選択特徴量対応）
# ----------------------------------------------------------------------
ml:
  feat_period: 14
  lags: [1,2,3,4,5]  # 軽量化
  rolling_window: 20
  horizon: 5
  target_type: classification
  model_type: lgbm

  # 選択された30特徴量（robust_model_features.jsonから）
  extra_features:
    # 基本リターン・価格特徴量
    - returns_2
    - returns_3
    - returns_5
    - returns_10
    - log_returns_2
    - log_returns_3
    - log_returns_5
    - log_returns_10
    - price_position_20
    - price_position_50
    - price_vs_sma20
    
    # RSI・テクニカル指標
    - rsi_14
    - rsi_7
    - rsi_21
    
    # ストキャスティクス
    - stoch_k
    - stoch_d
    - stoch_oversold
    - stoch_overbought
    
    # その他重要指標
    - mfi
    - trend_direction
    - cci_20
    - williams_r
    - ultimate_oscillator
    - support_distance
    - resistance_distance
    - support_strength
    - zscore
    - mean_reversion_20
    - mean_reversion_50
    - roc_10

  # モデルパラメータ（LightGBM最適化）
  model_params:
    objective: binary
    metric: binary_logloss
    boosting_type: gbdt
    num_leaves: 31
    learning_rate: 0.1
    feature_fraction: 0.8
    bagging_fraction: 0.8
    bagging_freq: 5
    min_child_samples: 20
    random_state: 42

# ----------------------------------------------------------------------
# 監視・レポート設定
# ----------------------------------------------------------------------
monitoring:
  enabled: true
  check_interval: 300
  
  metrics:
    - total_return
    - sharpe_ratio
    - max_drawdown
    - win_rate
    - profit_factor
    - calmar_ratio

# ----------------------------------------------------------------------
# 🎯 期待効果: -¥35,964損失 → 正のP&L達成
# ----------------------------------------------------------------------
# この99.2%精度モデルによる改善目標:
# 
# 📈 精度改善効果:
# - 学習精度: 99.2%
# - F1スコア: 99.2%
# - 2クラス分類（BUY/SELL）明確化
# - 30選択特徴量による効率化
# 
# 💰 収益改善期待:
# - 現状: -¥35,964損失
# - 目標: 正のP&L達成
# - 勝率改善: 0% → 50%以上
# - 取引精度向上による損失削減
# ----------------------------------------------------------------------