# =============================================================================
# ファイル名: config/aggressive_2x_target.yml
# 説明:
# 年2倍達成を目指す積極設定（レバレッジなし現物運用）
# - Bybit Testnetでの動作検証後、Bitbank本番運用に使用
# - risk_per_trade: 0.025（2.5%）でより積極的なリスクテイク
# - threshold: 0.04（4%）でエントリー機会を増加
# =============================================================================

# ----------------------------------------------------------------------
# データ取得設定
# ----------------------------------------------------------------------
data:
  exchange: bybit  # テスト時はbybit、本番時はbitbankに変更
  symbol: BTC/USDT  # テスト時はBTC/USDT、本番時はBTC/JPYに変更
  timeframe: 1h

  # ------ Bybit Testnet オプション（テスト時のみ） ------
  api_key: ${BYBIT_TESTNET_API_KEY}
  api_secret: ${BYBIT_TESTNET_API_SECRET}
  ccxt_options:
    defaultType: linear
    enableRateLimit: true
    urls:
      api: https://api-testnet.bybit.com
  # --------------------------------------

  # データ取得範囲
  since: "2021-01-01T00:00:00Z"
  limit: 20000
  paginate: true
  per_page: 500

# ----------------------------------------------------------------------
# 戦略設定 ―― MLStrategy（積極設定）
# ----------------------------------------------------------------------
strategy:
  type: single
  name: ml
  params:
    model_path: model/calibrated_model.pkl
    threshold: 0.04  # 0.05 → 0.04（より積極的エントリー）
    
    # 動的閾値調整パラメータ（積極設定）
    atr_multiplier: 0.6  # 0.5 → 0.6（より積極的調整）
    volatility_adjustment: true
    threshold_bounds: [0.01, 0.20]  # 上限を0.25 → 0.20に縮小
    
    thresholds_to_test:
      - 0.02  # より積極的な範囲
      - 0.04
      - 0.06
      - 0.08
      - 0.10
      - 0.15

# ----------------------------------------------------------------------
# リスク管理（積極設定）
# ----------------------------------------------------------------------
risk:
  risk_per_trade: 0.025  # 0.02 → 0.025（2.5%でより積極的）
  stop_atr_mult: 1.3   # 1.5 → 1.3（早めの損切りで回転率向上）
  dynamic_position_sizing:
    enabled: true
    formula: linear
  
  # Kelly基準を有効化（積極運用のため）
  kelly_criterion:
    enabled: true
    lookback_window: 30  # 50 → 30（より敏感に反応）
    max_fraction: 0.20  # 25% → 20%（少し保守的に）
    min_trades_required: 10

# ----------------------------------------------------------------------
# バックテスト（50万円想定）
# ----------------------------------------------------------------------
backtest:
  starting_balance: 500000.0  # 50万円に設定
  slippage_rate: 0.002  # Bitbank想定で少し高めに設定
  trade_log_csv: "./results/trade_log_aggressive.csv"
  aggregate_out_prefix: "./results/aggregate_aggressive"

# ----------------------------------------------------------------------
# パラメータ最適化
# ----------------------------------------------------------------------
optimizer:
  periods: []
  nbdevs:  []
  parallel: false
  max_workers: 1

# ----------------------------------------------------------------------
# ウォークフォワード分割
# ----------------------------------------------------------------------
walk_forward:
  train_window: 1200     # 1500 → 1200（より短期適応）
  test_window: 200       # 250 → 200（短期検証）
  step: 200              # より頻繁な再学習

# ----------------------------------------------------------------------
# 機械学習（ML）設定
# ----------------------------------------------------------------------
ml:
  feat_period: 14
  lags: [1,2,3,4,5,6,7,8,9,10,11,12]
  rolling_window: 15     # 20 → 15（より敏感な特徴量）
  horizon: 5
  target_type: classification
  model_type: lgbm

  # アンサンブルモデル設定（高精度のため有効化）
  ensemble:
    enabled: true  # false → true（精度向上のため）
    method: stacking
    weights: null
    
    base_models:
      - type: lgbm
        n_estimators: 89
        max_depth: 9
        learning_rate: 0.09558059446177633
        bagging_fraction: 0.6
        lambda_l1: 1.0
        lambda_l2: 0.5
      - type: rf
        n_estimators: 80   # 100 → 80（高速化）
        max_depth: 8
        min_samples_split: 5
        min_samples_leaf: 2
      - type: xgb
        n_estimators: 80   # 100 → 80（高速化）
        max_depth: 7
        learning_rate: 0.1
        subsample: 0.8
        colsample_bytree: 0.8
    
    meta_model:
      type: lr
      C: 1.0
      max_iter: 1000

  # 拡張特徴量（VIX統合・性能向上版）
  extra_features:
    # 基本テクニカル指標
    - rsi_14
    - macd
    - rci_9
    - volume_zscore
    - day_of_week
    - hour_of_day
    - mochipoyo_long_signal
    - mochipoyo_short_signal
    # 高度テクニカル指標
    - stoch
    - bb
    - willr_14
    - adx
    - cmf_20
    - fisher
    - advanced_signals
    # VIX恐怖指数統合（新機能）
    - vix
    # OI・ボリューム分析
    - oi

  # Optuna設定（積極最適化）
  optuna:
    n_trials: 15  # 10 → 15（より徹底的な最適化）
    timeout: 450  # 300 → 450（より長時間の最適化）
    direction: maximize
    sampler:
      name: TPESampler
    pruner:
      name: MedianPruner
      n_startup_trials: 5
      n_warmup_steps: 10
      interval_steps: 1

  # モデルパラメータ（最適化済み）
  model_params:
    n_estimators: 89
    max_depth: 9
    learning_rate: 0.09558059446177633
    bagging_fraction: 0.6
    lambda_l1: 1.0
    lambda_l2: 0.5

  # ハイパーパラメータ探索範囲
  model_params_search_space:
    max_depth:        [6,9,12]  # 範囲を狭めて高精度に
    learning_rate:    [0.05,0.1,0.15]  # より高い学習率
    feature_fraction: [0.8,1.0]  # より多くの特徴量を使用
    bagging_fraction: [0.6,0.8,1.0]
    lambda_l1:        [0.5,1.0,1.5]  # より強い正則化
    lambda_l2:        [0.5,1.0,1.5]

  # モデルキャリブレーション設定
  calibration:
    method: sigmoid
    cv: prefit

# ----------------------------------------------------------------------
# VIX恐怖指数統合設定（新機能）
# ----------------------------------------------------------------------
vix_integration:
  enabled: true
  risk_off_threshold: 25    # VIX 25以上でリスクオフ判定
  panic_threshold: 35       # VIX 35以上でパニック判定
  spike_multiplier: 2.0     # VIXスパイク時の閾値倍数

# ----------------------------------------------------------------------
# パフォーマンス向上設定（新機能）
# ----------------------------------------------------------------------
performance_enhancements:
  # エントリー精度向上
  confidence_filter: 0.65           # 65%以上の確信度でのみエントリー
  
  # 利確最適化
  partial_profit_levels: [0.3, 0.5] # 30%, 50%利益で段階的利確
  trailing_stop: true               # トレーリングストップ有効
  
  # 取引機会拡大
  multiple_timeframe: false         # マルチタイムフレーム（将来拡張用）
  pair_expansion: false             # 複数ペア対応（将来拡張用）