# =============================================================================
# ファイル名: config/default.yml
# 説明:
# Crypto-Bot 全体設定ファイル（データ取得・戦略・ML・リスク・バックテストなど）
# - 取引ペア・期間・MLモデル・リスクパラメータ等の主要設定を一元管理
# - extra_featuresに追加したいテクニカル指標を記載することで柔軟に特徴量拡張が可能
# =============================================================================

# ----------------------------------------------------------------------
# データ取得設定
# ----------------------------------------------------------------------
data:
  exchange: bybit
  symbol: BTC/USDT
  timeframe: 1h

  # ------ Bybit Testnet オプション ------
  api_key: ${BYBIT_TESTNET_API_KEY}    # .env から読み込み
  api_secret: ${BYBIT_TESTNET_API_SECRET}  # .env から読み込み
  ccxt_options:
    defaultType: linear
    enableRateLimit: true
    urls:
      api: https://api-testnet.bybit.com
  # --------------------------------------

  # データ取得範囲
  since: "2021-01-01T00:00:00Z"
  limit: 20000          # 20000 本 ≒ 2 年弱（1h足）
  paginate: true
  per_page: 500

# ----------------------------------------------------------------------
# 戦略設定 ―― MLStrategy
# ----------------------------------------------------------------------
strategy:
  name: ml_strategy
  params:
    model_path: model/calibrated_model.pkl
    threshold: 0.1
    thresholds_to_test:
      - 0.05
      - 0.10
      - 0.15
      - 0.20
      - 0.30
      - 0.40
      - 0.50

# ----------------------------------------------------------------------
# リスク管理
# ----------------------------------------------------------------------
risk:
  risk_per_trade: 0.01
  stop_atr_mult: 2.0
  dynamic_position_sizing:
    enabled: true
    formula: linear

# ----------------------------------------------------------------------
# バックテスト
# ----------------------------------------------------------------------
backtest:
  starting_balance: 10000.0
  slippage_rate: 0.001
  trade_log_csv: "./results/trade_log.csv"
  aggregate_out_prefix: "./results/aggregate"

# ----------------------------------------------------------------------
# パラメータ最適化（テクニカル用/未使用可）
# ----------------------------------------------------------------------
optimizer:
  periods: []
  nbdevs:  []
  parallel: false
  max_workers: 1

# ----------------------------------------------------------------------
# ウォークフォワード分割
# ----------------------------------------------------------------------
walk_forward:
  train_window: 1500     # 1500本 ≒ 2か月
  test_window: 250       # 250本 ≒ 10日
  step: 250              # テスト窓ごとにスライド

# ----------------------------------------------------------------------
# 機械学習（ML）設定
# ----------------------------------------------------------------------
ml:
  feat_period: 14                 # ATR等で使う期間
  lags: [1,2,3,4,5,6,7,8,9,10,11,12]
  rolling_window: 20
  horizon: 5                      # 何足先をターゲットにするか
  target_type: classification
  model_type: lgbm                # lgbm/rf/xgb

  # ==========================
  # extra_features 例
  # - rsi_14      : RSI(14)
  # - macd        : MACD（デフォルトパラメータ）
  # - rci_9       : RCI(9)
  # - sma_200     : 単純移動平均(200)
  # - ema_50      : 指数移動平均(50)
  # - volume_zscore: 出来高のZスコア
  # - day_of_week : 曜日（0=月, 6=日）
  # - hour_of_day : 時間（0〜23）
  # 例: ["rsi_14", "macd", "rci_9", "volume_zscore", "day_of_week", "hour_of_day"]
  # ==========================
  extra_features:
    - rsi_14
    - macd
    - rci_9
    - volume_zscore
    - day_of_week
    - hour_of_day
    - mochipoyo_long_signal
    - mochipoyo_short_signal

  # Optuna（ハイパーパラ最適化）設定
  optuna:
    n_trials: 30
    timeout: 900
    direction: maximize
    sampler:
      name: TPESampler
    pruner:
      name: MedianPruner
      n_startup_trials: 5
      n_warmup_steps: 10
      interval_steps: 1

  # 初期モデルパラメータ
  model_params:
    n_estimators: 89
    max_depth: 9
    learning_rate: 0.09558059446177633
    bagging_fraction: 0.6      # ←ここだけ
    lambda_l1: 1.0             # ←ここだけ
    lambda_l2: 0.5             # ←ここだけ
    # reg_alpha, reg_lambda, subsample, などは削除!!

  # ハイパーパラメータ探索範囲
  model_params_search_space:
    max_depth:        [3,6,9,12,15]
    learning_rate:    [0.001,0.01,0.05,0.1]
    feature_fraction: [0.6,0.8,1.0]
    bagging_fraction: [0.6,0.8,1.0]
    lambda_l1:        [0.0,0.1,0.5,1.0]
    lambda_l2:        [0.0,0.1,0.5,1.0]
    # reg_alpha, reg_lambda, subsample, などは削除!!

  # モデルキャリブレーション設定
  calibration:
    method: sigmoid
    cv: prefit