backtest:
  aggregate_out_prefix: ./results/aggregate_dxy_fear_greed
  slippage_rate: 0.001
  starting_balance: 10000.0
  trade_log_csv: ./results/trade_log_dxy_fear_greed.csv
data:
  api_key: ${BYBIT_TESTNET_API_KEY}
  api_secret: ${BYBIT_TESTNET_API_SECRET}
  ccxt_options:
    defaultType: linear
    enableRateLimit: true
    urls:
      api: https://api-testnet.bybit.com
  exchange: bybit
  limit: 10000
  paginate: true
  per_page: 500
  since: '2024-01-01T00:00:00Z'
  symbol: BTC/USDT
  timeframe: 1h
ml:
  extra_features:
  - rsi_14
  - macd
  - dxy
  - fear_greed
  feat_period: 14
  horizon: 5
  lags:
  - 1
  - 2
  - 3
  model_params:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 50
  model_type: lgbm
  rolling_window: 20
  target_type: classification
risk:
  dynamic_position_sizing:
    enabled: true
    formula: linear
  risk_per_trade: 0.02
  stop_atr_mult: 1.5
strategy:
  name: ml
  params:
    model_path: model/dxy_fear_greed_model.pkl
    threshold: 0.05
  type: single
walk_forward:
  step: 50
  test_window: 50
  train_window: 300