# 2年間DXY+Fear&Greed比較用設定
data:
  exchange: bybit
  symbol: BTC/USDT
  timeframe: 1h
  api_key: ${BYBIT_TESTNET_API_KEY}
  api_secret: ${BYBIT_TESTNET_API_SECRET}
  ccxt_options:
    defaultType: linear
    enableRateLimit: true
    urls:
      api: https://api-testnet.bybit.com
  since: "2022-01-01T00:00:00Z"  # 2年間
  limit: 20000
  paginate: true
  per_page: 500

strategy:
  type: single
  name: ml
  params:
    model_path: model/dxy_fear_greed_2year_model.pkl
    threshold: 0.05

risk:
  risk_per_trade: 0.02
  stop_atr_mult: 1.5
  dynamic_position_sizing:
    enabled: true
    formula: linear

backtest:
  starting_balance: 10000.0
  slippage_rate: 0.001
  trade_log_csv: "./results/trade_log_dxy_fear_greed_2year.csv"
  aggregate_out_prefix: "./results/aggregate_dxy_fear_greed_2year"

walk_forward:
  train_window: 1500
  test_window: 250
  step: 250

ml:
  feat_period: 14
  lags: [1,2,3]
  rolling_window: 20
  horizon: 5
  target_type: classification
  model_type: lgbm
  
  # DXY + Fear & Greed統合
  extra_features:
    - rsi_14
    - macd
    - volume_zscore
    - day_of_week
    - hour_of_day
    - dxy         # DXY・金利・マクロ経済（10特徴量）
    - fear_greed  # Fear & Greed Index（14特徴量）

  model_params:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 50