backtest:
  aggregate_out_prefix: ./results/aggregate_optimized
  slippage_rate: 0.001
  starting_balance: 10000.0
  trade_log_csv: ./results/trade_log_optimized.csv
data:
  api_key: ${BYBIT_TESTNET_API_KEY}
  api_secret: ${BYBIT_TESTNET_API_SECRET}
  ccxt_options:
    defaultType: linear
    enableRateLimit: true
    urls:
      api: https://api-testnet.bybit.com
  exchange: bybit
  limit: 2000
  paginate: true
  per_page: 200
  since: '2025-05-01T00:00:00Z'
  symbol: BTC/USDT
  timeframe: 1h
ml:
  extra_features:
  - rsi_14
  - macd
  - volume_zscore
  - day_of_week
  - hour_of_day
  - dxy
  - fear_greed
  - funding
  feat_period: 14
  horizon: 5
  lags:
  - 1
  - 2
  - 3
  model_params:
    learning_rate: 0.05      # Optuna最適化結果
    max_depth: 15           # Optuna最適化結果  
    n_estimators: 150       # より多く学習
    feature_fraction: 0.8   # Optuna最適化結果
    bagging_fraction: 1.0   # Optuna最適化結果
    lambda_l1: 0.5         # Optuna最適化結果
    lambda_l2: 0.5         # Optuna最適化結果
  model_type: lgbm
  rolling_window: 20
  target_type: classification
risk:
  dynamic_position_sizing:
    enabled: true
    formula: linear
  risk_per_trade: 0.02
  stop_atr_mult: 1.5
strategy:
  name: ml
  params:
    model_path: model/optimized_integration_model.pkl
    threshold: 0.05
  type: single
walk_forward:
  step: 100
  test_window: 100
  train_window: 400
