# 軽量版・取引開始テスト用設定
# INIT-5ハング問題解決のため最小限データ取得

data:
  exchange: bitbank
  symbol: BTC/JPY
  timeframe: 1h
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 1000

  # 最小限データ取得でハング回避
  since: "2025-01-01T00:00:00Z"
  limit: 100  # 8000→100に大幅削減
  paginate: true
  per_page: 50  # 200→50に削減

strategy:
  type: single
  name: ml
  params:
    model_path: /app/model.pkl
    threshold: 0.02

risk:
  risk_per_trade: 0.005
  stop_atr_mult: 1.2
  kelly_criterion:
    enabled: true
    max_fraction: 0.05

live:
  mode: live
  trade_interval: 60
  min_order_size: 0.0001  # Bitbank最小単位に合わせて調整
  max_order_size: 0.0005
  margin_trading:
    enabled: true   # 信用取引有効
    leverage: 1.0   # 1倍レバレッジ
    position_type: "both"  # ロング・ショート両対応
  
  # Bitbank固有設定
  bitbank_settings:
    min_btc_amount: 0.0001  # BTC最小取引量
    max_retries: 3          # API失敗時リトライ回数
    retry_delay: 5          # リトライ間隔（秒）

# 軽量ML設定
ml:
  feat_period: 14
  lags: [1,2,3]  # 12→3に削減
  rolling_window: 10  # 20→10に削減
  horizon: 3  # 5→3に削減
  target_type: classification
  model_type: lgbm
  
  # 外部データ無効化でハング回避
  extra_features:
    - rsi_14
    - macd
    - sma_50
    # VIX等の外部データを一時無効化