# 軽量版設定（3特徴量）- 初期化高速化・安定性重視
# 初期起動時の動作確認用

data:
  exchange: bitbank
  symbol: BTC/JPY
  timeframe: 1h
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 1000

  # 最小限データ取得で高速化
  since: "2025-07-12T05:00:00Z"  # 7日前からのデータ取得
  limit: 100  # 最小限のレコード数
  paginate: true
  per_page: 50

strategy:
  type: single
  name: ml
  params:
    model_path: /app/models/production/model.pkl  # 固定パス
    threshold: 0.05

risk:
  risk_per_trade: 0.005
  stop_atr_mult: 1.2
  atr_period: 10  # ATR計算期間短縮
  kelly_criterion:
    enabled: true
    max_fraction: 0.05

live:
  mode: live
  trade_interval: 30  # 30秒間隔
  min_order_size: 0.0001
  max_order_size: 0.0005
  margin_trading:
    enabled: true
    leverage: 1.0
    position_type: "both"

# 軽量ML設定（3特徴量のみ）
ml:
  feat_period: 14
  lags: [1,2,3]  # 最小限のラグ
  rolling_window: 10
  horizon: 3
  target_type: classification
  model_type: lgbm
  
  # 3つの基本特徴量のみ（外部データ無効化）
  extra_features:
    - rsi_14
    - macd
    - sma_50