# data_paths.yml - データパス設定統一管理
# Phase 14.6: パス管理統一・環境依存除去

# メインデータファイルパス
main_data:
  btc_usd_hourly: "data/btc_usd_2024_hourly.csv"
  backup_pattern: "data/btc_usd_2024_hourly_backup_*.csv"

# 将来拡張データパス
historical_data:
  btc_usd_2023: "data/historical/btc_usd_2023_hourly.csv"
  btc_usd_2022: "data/historical/btc_usd_2022_hourly.csv"

# 処理済みデータパス  
processed_data:
  features_97: "data/processed/features_97_processed.pkl"
  ml_ready: "data/processed/ml_ready_dataset.pkl"

# 環境変数対応
environment:
  data_root: "${DATA_ROOT:-data}"
  backup_root: "${BACKUP_ROOT:-data}"

# 品質設定
data_quality:
  max_price: 150000
  min_price: 10000
  max_volume: 100000
  backup_retention_days: 30
