backtest:
  slippage_rate: 0.001
  starting_balance: 10000.0
bitbank:
  day_trading:
    auto_close_before_rollover: true
    enabled: true
    interest_rate: 0.0004
    rollover_time: 00:00:00
  fee_optimization:
    enabled: true
    maker_fee: -0.0002
    min_profit_after_fees: 0.002
    prefer_maker: true
    taker_fee: 0.0012
  order_management:
    max_open_orders: 30
    queue_enabled: true
    rate_limit:
      get_requests: 10
      post_requests: 6
data:
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false
  exchange: bitbank
  exponential_backoff: true
  fetch_retries: 3
  limit: 200
  multi_timeframe_data:
    base_timeframe: 1h
    target_timeframes:
      15m:
        method: interpolation
        min_points: 10
      1h:
        method: direct
        min_points: 10
      4h:
        api_fetch: false
        method: aggregation
        min_points: 8
  paginate: true
  per_page: 100
  since_hours: 48
  symbol: BTC/JPY
  timeframe: 1h
live:
  margin_trading:
    enabled: true
    leverage: 1.0
    position_type: both
  max_order_size: 0.0005
  min_order_size: 0.0001
  mode: backtest
  starting_balance: 10000.0
ml:
  confidence_threshold: 0.5
  ensemble:
    confidence_threshold: 0.5
    enabled: true
    method: trading_stacking
    models:
    - lgbm
    - xgb
    - rf
    risk_adjustment: true
  extra_features:
  - close_lag_1
  - close_lag_3
  - volume_lag_1
  - volume_lag_4
  - volume_lag_5
  - returns_1
  - returns_2
  - returns_3
  - returns_5
  - returns_10
  - ema_5
  - ema_10
  - ema_20
  - ema_50
  - ema_100
  - ema_200
  - rsi_14
  - rsi_oversold
  - rsi_overbought
  - atr_14
  - volatility_20
  - hour
  - day_of_week
  - is_weekend
  - is_asian_session
  - is_us_session
  feat_period: 14
  horizon: 5
  lags:
  - 1
  - 3
  model_type: lgbm
  rolling_window: 10
  target_type: classification
risk:
  atr_period: 20
  kelly_criterion:
    enabled: true
    max_fraction: 0.03
  risk_per_trade: 0.01
  stop_atr_mult: 1.2
strategy:
  confidence_threshold: 0.5
  name: multi_timeframe_ensemble
  params:
    model_path: /app/models/production/model.pkl
    threshold: 0.01
    volatility_adjustment: true
  type: multi_timeframe_ensemble
