# Phase 3.3: 改善モデル バックテスト設定
# 125特徴量統一システム・RSIフォールバック機能・固定予測問題修正後のテスト

data:
  exchange: bitbank
  symbol: BTC/JPY
  timeframe: 1h
  start_date: 2024-12-01
  end_date: 2025-01-30
  data_source: api

ml:
  enabled: true
  model_path: models/production/model.pkl
  confidence_threshold: 0.45  # Phase 2で最適化された値
  extra_features:
    # 基本価格特徴量
    - close_lag_1
    - close_lag_2
    - close_lag_3
    - close_lag_4
    - close_lag_5
    - volume_lag_1
    - volume_lag_2
    - volume_lag_3
    - volume_lag_4
    - volume_lag_5
    - returns_1
    - returns_2
    - returns_3
    - returns_5
    - returns_10
    - log_returns_1
    - log_returns_2
    - log_returns_3
    - log_returns_5
    - log_returns_10
    
    # 移動平均
    - sma_5
    - sma_10
    - sma_20
    - sma_50
    - sma_100
    - sma_200
    - ema_5
    - ema_10
    - ema_20
    - ema_50
    - ema_100
    - ema_200
    
    # テクニカル指標
    - price_position_20
    - price_position_50
    - price_vs_sma20
    - bb_position
    - intraday_position
    - bb_upper
    - bb_middle
    - bb_lower
    - bb_width
    - bb_squeeze
    
    # RSI（フォールバック機能付き）
    - rsi_14
    - rsi_7
    - rsi_21
    - rsi_oversold
    - rsi_overbought
    
    # MACD
    - macd
    - macd_signal
    - macd_hist
    - macd_cross_up
    - macd_cross_down
    
    # Stochastic
    - stoch_k
    - stoch_d
    - stoch_oversold
    - stoch_overbought
    
    # ATR・ボラティリティ
    - atr_14
    - atr_7
    - atr_21
    - volatility_20
    - volatility_50
    - high_low_ratio
    - true_range
    - volatility_ratio
    
    # 出来高
    - volume_sma_20
    - volume_ratio
    - volume_trend
    - vwap
    - vwap_distance
    - obv
    - obv_sma
    - cmf
    - mfi
    - ad_line
    
    # トレンド
    - adx_14
    - plus_di
    - minus_di
    - trend_strength
    - trend_direction
    - cci_20
    - williams_r
    - ultimate_oscillator
    
    # サポート・レジスタンス
    - support_distance
    - resistance_distance
    - support_strength
    - volume_breakout
    - price_breakout_up
    - price_breakout_down
    
    # キャンドルパターン
    - doji
    - hammer
    - engulfing
    - pinbar
    
    # 統計
    - skewness_20
    - kurtosis_20
    - zscore
    - mean_reversion_20
    - mean_reversion_50
    
    # 時間
    - hour
    - day_of_week
    - is_weekend
    - is_asian_session
    - is_european_session
    - is_us_session
    
    # 高度指標
    - roc_10
    - roc_20
    - trix
    - mass_index
    - keltner_upper
    - keltner_lower
    - donchian_upper
    - donchian_lower
    - ichimoku_conv
    - ichimoku_base
    - price_efficiency
    - trend_consistency
    - volume_price_correlation
    - volatility_regime
    - momentum_quality
    - market_phase
    - momentum_14

strategy:
  name: multi_timeframe_ensemble
  confidence_threshold: 0.45
  dynamic_threshold:
    enabled: true
    atr_adjustment: true
    volatility_adjustment: true
    vix_adjustment: false  # 外部データ無効化

risk:
  max_position_size: 0.1
  stop_loss_pct: 0.02
  take_profit_pct: 0.03
  kelly_fraction: 0.25

backtest:
  initial_balance: 100000
  commission: 0.0012  # Bitbank平均手数料
  slippage: 0.001

# Phase 3.3: 改善モデル検証項目
# - 125特徴量システム完全対応
# - RSIフォールバック機能動作確認
# - 固定予測問題修正効果確認
# - BUY/SELLバランス改善確認
# - エントリー頻度適正化確認