# JPY建てバックテスト専用設定
# 日本市場特性・税制考慮・JPY建て収益計算対応

# ----------------------------------------------------------------------
# データ取得設定（JPY建て）
# ----------------------------------------------------------------------
data:
  exchange: bitbank
  symbol: BTC/JPY
  timeframe: 1h
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  
  # 日本市場データ取得設定
  since: "2024-01-01T00:00:00Z"
  limit: 1000
  paginate: true
  per_page: 100
  
  # 日本市場特性考慮
  japanese_market:
    enabled: true
    timezone: "Asia/Tokyo"
    consider_holidays: true
    consider_business_hours: true
    activity_score_threshold: 0.7

# ----------------------------------------------------------------------
# JPY建て戦略設定
# ----------------------------------------------------------------------
strategy:
  type: single
  name: ml
  params:
    model_path: /app/model.pkl
    threshold: 0.05
    
    # 日本市場特性考慮
    japanese_market_filter:
      enabled: true
      min_activity_score: 0.5
      avoid_holidays: true
      avoid_year_end: true

# ----------------------------------------------------------------------
# JPY建てリスク管理
# ----------------------------------------------------------------------
risk:
  risk_per_trade: 0.02
  stop_atr_mult: 2.0
  
  # JPY建て設定
  base_currency: JPY
  position_sizing:
    method: fixed_jpy
    fixed_amount_jpy: 200000  # 20万円固定
    max_position_jpy: 1000000  # 100万円上限
  
  # Kelly基準（JPY建て）
  kelly_criterion:
    enabled: true
    lookback_window: 50
    max_fraction: 0.25
    min_trades_required: 10
    currency: JPY

# ----------------------------------------------------------------------
# JPY建てバックテスト設定
# ----------------------------------------------------------------------
backtest:
  starting_balance: 1000000.0  # 100万円
  base_currency: JPY
  
  # 日本市場特性考慮
  japanese_market:
    enabled: true
    exclude_holidays: false  # 祝日も取引（暗号通貨は24/7）
    exclude_year_end: false  # 年末年始も取引
    apply_activity_score: true  # 市場活動度スコア適用
  
  # JPY建て手数料設定
  slippage_rate: 0.001
  commission_rate: 0.0012  # Bitbankテイカー手数料
  
  # 税制考慮
  tax_settings:
    enabled: true
    tax_rate: 0.20  # 雑所得20%
    include_consumption_tax: false
    calculate_net_profit: true
  
  # 出力設定
  trade_log_csv: "./results/jpy_backtest_trades.csv"
  aggregate_out_prefix: "./results/jpy_backtest_summary"
  japanese_report: "./results/jpy_backtest_report.txt"

# ----------------------------------------------------------------------
# JPY建てML設定
# ----------------------------------------------------------------------
ml:
  feat_period: 14
  lags: [1, 2, 3, 4, 5]
  rolling_window: 20
  horizon: 5
  target_type: classification
  model_type: lgbm
  
  # 日本市場特性特徴量
  japanese_market_features:
    enabled: true
    features:
      - is_japanese_holiday
      - is_weekend
      - is_year_end_period
      - is_business_hours
      - market_activity_score
      - hour_of_day_jst
      - day_of_week_jst
  
  # 基本特徴量
  extra_features:
    - rsi_14
    - macd
    - sma_50
    - sma_200
    - bb_upper
    - bb_lower
    - atr_14
    - volume_sma
    
  # 外部データ（JPY建て考慮）
  external_data:
    enabled: true
    vix:
      enabled: true
      jpy_correlation: true
    macro:
      enabled: true
      usd_jpy_rate: true
    fear_greed:
      enabled: true
      japanese_sentiment: true

# ----------------------------------------------------------------------
# JPY建てライブ設定
# ----------------------------------------------------------------------
live:
  mode: paper  # バックテスト用はpaper
  trade_interval: 60
  
  # JPY建て注文設定
  base_currency: JPY
  min_order_size_jpy: 1000  # 1000円
  max_order_size_jpy: 100000  # 10万円
  
  # Bitbank JPY設定
  bitbank_jpy_settings:
    min_btc_amount: 0.0001
    price_precision: 0
    amount_precision: 4
    
  # 日本市場考慮
  japanese_market:
    enabled: true
    avoid_low_activity: true
    min_activity_score: 0.6