backtest:
  aggregate_out_prefix: ./results/quick_profit_test
  commission_rate: 0.0005
  slippage_rate: 0.001
  starting_balance: 10000.0
  trade_log_csv: ./results/quick_profit_test_log.csv
data:
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false
  exchange: bitbank
  exponential_backoff: true
  fetch_retries: 3
  limit: 400
  paginate: true
  per_page: 200
  since_hours: 96
  symbol: BTC/JPY
  timeframe: 1h
  weekend_data: true
  weekend_extension_hours: 72
ml:
  extra_features:
  - rsi_14
  - macd
  - bb
  - stoch
  - sma_20
  - ema_50
  - volume_ratio
  - atr_14
  - trend_strength
  - momentum_14
  feat_period: 14
  horizon: 3
  lags:
  - 1
  - 2
  - 3
  model_params:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 50
    random_state: 42
  model_type: lgbm
  rolling_window: 10
  target_type: classification
monitoring:
  enabled: false
risk:
  dynamic_position_sizing:
    enabled: true
    formula: linear
  kelly_criterion:
    enabled: true
    lookback_window: 20
    max_fraction: 0.25
    min_trades_required: 5
  risk_per_trade: 0.02
  stop_atr_mult: 2.0
strategy:
  name: ml
  params:
    atr_multiplier: 0.5
    model_path: models/production/integrated_127_features_model.pkl
    threshold: 0.05
    threshold_bounds:
    - 0.01
    - 0.25
    volatility_adjustment: true
  type: single
walk_forward:
  step: 24
  test_window: 48
  train_window: 240
