backtest:
  commission: 0.0012
  end_date: '2024-03-31'
  initial_balance: 10000
  position_sizing:
    max_position_size: 0.95
    method: kelly_criterion
    min_position_size: 0.01
  risk_management:
    max_drawdown: 0.15
    stop_loss: 0.03
    take_profit: 0.06
  start_date: '2024-01-01'
data:
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false
  exchange: bitbank
  exponential_backoff: true
  fetch_retries: 3
  limit: 400
  paginate: true
  per_page: 200
  since_hours: 96
  symbol: BTC/JPY
  timeframe: 1h
  weekend_data: true
  weekend_extension_hours: 72
external_data:
  enabled: false
logging:
  file: logs/simple_97_backtest.log
  level: INFO
ml:
  extra_features:
  - ema_20
  - rsi_14
  - macd
  - cmf
  - trend_strength
  - volatility_regime
  - momentum_quality
  - market_phase
  - day_of_week
  feat_period: 14
  lags:
  - 1
  - 3
  log_returns: false
  return_periods:
  - 1
  - 2
  - 3
  - 5
  - 10
  rolling_window: 14
  target:
    buy_threshold: 0.005
    lookahead: 3
    method: threshold
    sell_threshold: -0.005
    type: classification
output:
  generate_report: true
  results_dir: results/simple_97_backtest
  save_equity_curve: true
  save_metrics: true
  save_trades: true
strategy:
  name: ml
  params:
    atr_multiplier: 0.3
    model_path: models/production/model.pkl
    threshold: 0.02
    threshold_bounds:
    - 0.01
    - 0.08
    volatility_adjustment: true
  type: single
