backtest:
  commission: 0.0012
  end_date: '2024-06-30'
  initial_balance: 10000
  position_sizing:
    max_position_size: 0.95
    method: kelly_criterion
    min_position_size: 0.01
    risk_free_rate: 0.001
  risk_management:
    max_drawdown: 0.15
    stop_loss: 0.03
    take_profit: 0.06
    trailing_stop: 0.02
  start_date: '2024-01-01'
data:
  api_key: ${BITBANK_API_KEY}
  api_secret: ${BITBANK_API_SECRET}
  ccxt_options:
    enableRateLimit: true
    rateLimit: 20000
    timeout: 60000
    verbose: false
  exchange: bitbank
  exponential_backoff: true
  fetch_retries: 3
  limit: 400
  paginate: true
  per_page: 200
  since_hours: 96
  symbol: BTC/JPY
  timeframe: 1h
  weekend_data: true
  weekend_extension_hours: 72
external_data:
  enabled: false
logging:
  file: logs/97_features_backtest.log
  level: INFO
ml:
  confidence_threshold: 0.5
  ensemble:
    confidence_threshold: 0.5
    enabled: true
    method: trading_stacking
    model_weights:
    - 0.5
    - 0.3
    - 0.2
    models:
    - lgbm
    - xgb
    - rf
    risk_adjustment: true
  extra_features:
  - close_lag_1
  - close_lag_3
  - volume_lag_1
  - volume_lag_4
  - volume_lag_5
  - returns_1
  - returns_2
  - returns_3
  - returns_5
  - returns_10
  - ema_5
  - ema_10
  - ema_20
  - ema_50
  - ema_100
  - ema_200
  - price_position_20
  - price_position_50
  - price_vs_sma20
  - bb_position
  - intraday_position
  - bb_upper
  - bb_middle
  - bb_lower
  - bb_width
  - bb_squeeze
  - rsi_14
  - rsi_oversold
  - rsi_overbought
  - macd
  - macd_signal
  - macd_hist
  - macd_cross_up
  - macd_cross_down
  - stoch_k
  - stoch_d
  - stoch_oversold
  - stoch_overbought
  - atr_14
  - volatility_20
  - volume_sma_20
  - volume_ratio
  - volume_trend
  - vwap
  - vwap_distance
  - obv
  - obv_sma
  - cmf
  - mfi
  - ad_line
  - adx_14
  - plus_di
  - minus_di
  - trend_strength
  - trend_direction
  - cci_20
  - williams_r
  - ultimate_oscillator
  - momentum_14
  - support_distance
  - resistance_distance
  - support_strength
  - volume_breakout
  - price_breakout_up
  - price_breakout_down
  - doji
  - hammer
  - engulfing
  - pinbar
  - zscore
  - close_std_10
  - hour
  - day_of_week
  - is_weekend
  - is_asian_session
  - is_us_session
  - roc_10
  - roc_20
  - trix
  - mass_index
  - keltner_upper
  - keltner_lower
  - donchian_upper
  - donchian_lower
  - ichimoku_conv
  - ichimoku_base
  - price_efficiency
  - trend_consistency
  - volume_price_correlation
  - volatility_regime
  - momentum_quality
  - market_phase
  feat_period: 14
  lags:
  - 1
  - 3
  log_returns: false
  return_periods:
  - 1
  - 2
  - 3
  - 5
  - 10
  rolling_window: 14
  target:
    balance_data: true
    balance_method: undersample
    buy_threshold: 0.005
    lookahead: 3
    method: threshold
    sell_threshold: -0.005
    type: classification
optimization_info:
  deleted_features: 30
  efficiency_gain: 約24%の計算効率向上
  expected_improvement: 重複除去による予測精度向上
  optimized_features: 97
  original_features: 127
  validation_target: 同等以上の損益・勝率維持
output:
  generate_report: true
  results_dir: results/97_features_backtest
  save_equity_curve: true
  save_metrics: true
  save_trades: true
risk:
  atr_period: 14
  risk_per_trade: 0.02
  stop_atr_mult: 2.5
strategy:
  name: multi_timeframe_ensemble
  params:
    atr_multiplier: 0.3
    max_volatility_adj: 0.03
    ml:
      feat_period: 14
      horizon: 5
      lags:
      - 1
      - 2
      - 3
      model_type: lgbm
      rolling_window: 10
      target_type: classification
    model_path: models/production/model.pkl
    performance_adj_range:
    - -0.003
    - 0.005
    threshold: 0.01
    threshold_bounds:
    - 0.005
    - 0.1
    volatility_adjustment: true
  type: multi_timeframe_ensemble
