# 指標組み合わせテスト用サンプル設定
# 97特徴量から選択した組み合わせでバックテストを実行

# === Sample 1: RSI + MACD + EMA トレンドフォロー ===
rsi_macd_ema_trend:
  name: "RSI + MACD + EMA Trend Following"
  description: "RSI・MACD・EMAを使ったトレンドフォロー戦略"
  feature_subset:
    # RSI系
    - rsi_14
    - rsi_oversold
    - rsi_overbought
    # MACD系
    - macd
    - macd_signal
    - macd_hist
    - macd_cross_up
    - macd_cross_down
    # EMA系
    - ema_5
    - ema_10
    - ema_20
    - ema_50
    # 基本価格情報
    - close_lag_1
    - returns_1
    - volume_ratio

# === Sample 2: ボリンジャーバンド + ストキャスティクス ===
bb_stochastic_mean_reversion:
  name: "Bollinger Bands + Stochastic Mean Reversion"
  description: "ボリンジャーバンド・ストキャスティクスを使った逆張り戦略"
  feature_subset:
    # ボリンジャーバンド系
    - bb_position
    - bb_upper
    - bb_middle
    - bb_lower
    - bb_width
    - bb_squeeze
    # ストキャスティクス系
    - stoch_k
    - stoch_d
    - stoch_oversold
    - stoch_overbought
    # ボラティリティ
    - atr_14
    - volatility_20
    # 基本情報
    - close_lag_1
    - price_vs_sma20

# === Sample 3: ADX + DMI トレンド強度 ===
adx_dmi_trend_strength:
  name: "ADX + DMI Trend Strength"
  description: "ADX・DMIを使ったトレンド強度判定戦略"
  feature_subset:
    # ADX・DMI系
    - adx_14
    - plus_di
    - minus_di
    - trend_strength
    - trend_direction
    # 補助指標
    - cci_20
    - williams_r
    - momentum_14
    # ボリューム
    - volume_trend
    - volume_breakout
    # 基本情報
    - close_lag_1
    - returns_3

# === Sample 4: VWAP + OBV ボリューム分析 ===
vwap_obv_volume_analysis:
  name: "VWAP + OBV Volume Analysis"  
  description: "VWAP・OBVを使ったボリューム分析戦略"
  feature_subset:
    # VWAP系
    - vwap
    - vwap_distance
    # ボリューム系
    - obv
    - obv_sma
    - volume_sma_20
    - volume_ratio
    - volume_trend
    - volume_breakout
    # マネーフロー系
    - cmf
    - mfi
    - ad_line
    # 基本情報
    - close_lag_1
    - returns_2

# === Sample 5: 一目均衡表 + ドンチャンチャネル ===
ichimoku_donchian_breakout:
  name: "Ichimoku + Donchian Breakout"
  description: "一目均衡表・ドンチャンチャネルを使ったブレイクアウト戦略"
  feature_subset:
    # 一目均衡表
    - ichimoku_conv
    - ichimoku_base
    # ドンチャンチャネル
    - donchian_upper
    - donchian_lower
    # ケルトナーチャネル
    - keltner_upper
    - keltner_lower
    # ブレイクアウト系
    - price_breakout_up
    - price_breakout_down
    - support_distance
    - resistance_distance
    - support_strength
    # 基本情報
    - close_lag_1
    - atr_14

# === Sample 6: シンプル時間足分析 ===
simple_time_analysis:
  name: "Simple Time-based Analysis"
  description: "時間軸・セッション分析中心のシンプル戦略"
  feature_subset:
    # 時間系
    - hour
    - day_of_week
    - is_weekend
    - is_asian_session
    - is_us_session
    # シンプル指標
    - ema_20
    - rsi_14
    - volume_ratio
    - returns_1
    - close_lag_1
    # ボラティリティ
    - atr_14
    - volatility_20

# === Sample 7: キャンドルスティックパターン ===
candlestick_patterns:
  name: "Candlestick Pattern Analysis"
  description: "ローソク足パターンを重視した戦略"
  feature_subset:
    # キャンドルスティックパターン
    - doji
    - hammer
    - engulfing
    - pinbar
    # サポート・レジスタンス
    - support_distance
    - resistance_distance
    - support_strength
    - price_breakout_up
    - price_breakout_down
    # 基本指標
    - rsi_14
    - close_lag_1
    - atr_14
    - volume_ratio

# === Sample 8: 高頻度スキャルピング用 ===
scalping_short_term:
  name: "High-Frequency Scalping"
  description: "短期スキャルピング向け高速指標組み合わせ"
  feature_subset:
    # 短期ラグ
    - close_lag_1
    - close_lag_3
    - volume_lag_1
    - returns_1
    - returns_2
    # 短期EMA
    - ema_5
    - ema_10
    - price_position_20
    # ボラティリティ
    - atr_14
    - bb_width
    # その他
    - intraday_position
    - volume_ratio

# === 使用方法 ===
# 1. base_backtest_config.yml をコピー
# 2. 上記のサンプルから feature_subset をコピーして ml.feature_subset に設定
# 3. バックテスト実行:
#    python -m crypto_bot.main backtest --config config/backtest/your_test_config.yml

# 例: RSI + MACD + EMA テスト用設定
# ml:
#   feature_subset:
#     - rsi_14
#     - rsi_oversold
#     - rsi_overbought
#     - macd
#     - macd_signal
#     - macd_hist
#     - ema_20
#     - close_lag_1
#     - returns_1