apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-bot-config
  namespace: crypto-bot
  labels:
    app: crypto-bot
data:
  MODE: "paper"
  LOG_LEVEL: "INFO"
  
  # Trading configuration
  DEFAULT_CONFIG: |
    data:
      exchange: bybit_testnet
      symbol: BTC/USDT
      interval: 1h
      limit: 1000
    
    strategy:
      type: single
      name: ml
      params:
        model_path: model/calibrated_model.pkl
        threshold: 0.1
    
    risk:
      base_risk: 0.02
      dynamic_position_sizing: true
      max_position_size: 0.1
      stop_loss_atr_multiplier: 2.0
    
    ml:
      extra_features:
        - rsi
        - macd
        - volume_zscore
        - hour_of_day
        - day_of_week
  
  # Health check configuration
  HEALTH_CHECK_INTERVAL: "30"
  STARTUP_PROBE_DELAY: "60"
  
  # Monitoring configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "8080"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-bot-config-dev
  namespace: crypto-bot-dev
  labels:
    app: crypto-bot
    environment: dev
data:
  MODE: "paper"
  LOG_LEVEL: "DEBUG"
  HEALTH_CHECK_INTERVAL: "15"
  STARTUP_PROBE_DELAY: "30"
  METRICS_ENABLED: "true"
  METRICS_PORT: "8080"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-bot-config-prod
  namespace: crypto-bot-prod
  labels:
    app: crypto-bot
    environment: prod
data:
  MODE: "live"
  LOG_LEVEL: "INFO"
  HEALTH_CHECK_INTERVAL: "60"
  STARTUP_PROBE_DELAY: "120"
  METRICS_ENABLED: "true"
  METRICS_PORT: "8080"