# Pod Disruption Budget for default namespace
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: crypto-bot-pdb
  namespace: crypto-bot
  labels:
    app: crypto-bot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: crypto-bot

---
# PDB for development environment
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: crypto-bot-pdb-dev
  namespace: crypto-bot-dev
  labels:
    app: crypto-bot
    environment: dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: crypto-bot
      environment: dev

---
# PDB for production environment
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: crypto-bot-pdb-prod
  namespace: crypto-bot-prod
  labels:
    app: crypto-bot
    environment: prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: crypto-bot
      environment: prod