# NOTE: This is a template file. 
# In production, secrets should be created via kubectl or external secret management tools
# Example commands:
# kubectl create secret generic crypto-bot-secrets \
#   --from-literal=BYBIT_TESTNET_API_KEY=your-api-key \
#   --from-literal=BYBIT_TESTNET_API_SECRET=your-api-secret \
#   --namespace=crypto-bot

apiVersion: v1
kind: Secret
metadata:
  name: crypto-bot-secrets
  namespace: crypto-bot
  labels:
    app: crypto-bot
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  # echo -n "your-api-key" | base64
  BYBIT_TESTNET_API_KEY: ""
  BYBIT_TESTNET_API_SECRET: ""
  
  # Additional exchange API keys
  BITBANK_API_KEY: ""
  BITBANK_API_SECRET: ""
  BITFLYER_API_KEY: ""
  BITFLYER_API_SECRET: ""
  OKCOINJP_API_KEY: ""
  OKCOINJP_API_SECRET: ""
  
  # GCP Service Account Key for Cloud Monitoring
  GOOGLE_APPLICATION_CREDENTIALS_JSON: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: crypto-bot-secrets-dev
  namespace: crypto-bot-dev
  labels:
    app: crypto-bot
    environment: dev
type: Opaque
data:
  BYBIT_TESTNET_API_KEY: ""
  BYBIT_TESTNET_API_SECRET: ""
  GOOGLE_APPLICATION_CREDENTIALS_JSON: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: crypto-bot-secrets-prod
  namespace: crypto-bot-prod
  labels:
    app: crypto-bot
    environment: prod
type: Opaque
data:
  # Production secrets should use external secret management
  # Consider using External Secrets Operator or similar tools
  BYBIT_LIVE_API_KEY: ""
  BYBIT_LIVE_API_SECRET: ""
  GOOGLE_APPLICATION_CREDENTIALS_JSON: ""