{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crypto-bot.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crypto-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.bybitTestnetApiKey }}
  bybit-testnet-api-key: {{ .Values.secrets.bybitTestnetApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.bybitTestnetApiSecret }}
  bybit-testnet-api-secret: {{ .Values.secrets.bybitTestnetApiSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.bybitLiveApiKey }}
  bybit-live-api-key: {{ .Values.secrets.bybitLiveApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.bybitLiveApiSecret }}
  bybit-live-api-secret: {{ .Values.secrets.bybitLiveApiSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.bitbankApiKey }}
  bitbank-api-key: {{ .Values.secrets.bitbankApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.bitbankApiSecret }}
  bitbank-api-secret: {{ .Values.secrets.bitbankApiSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.bitflyerApiKey }}
  bitflyer-api-key: {{ .Values.secrets.bitflyerApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.bitflyerApiSecret }}
  bitflyer-api-secret: {{ .Values.secrets.bitflyerApiSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.okcoinjpApiKey }}
  okcoinjp-api-key: {{ .Values.secrets.okcoinjpApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.okcoinjpApiSecret }}
  okcoinjp-api-secret: {{ .Values.secrets.okcoinjpApiSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.gcpCredentialsJson }}
  gcp-credentials-json: {{ .Values.secrets.gcpCredentialsJson | b64enc | quote }}
  {{- end }}
{{- end }}