apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crypto-bot.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.config.metricsEnabled }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.config.metricsPort }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "crypto-bot.selectorLabels" . | nindent 4 }}